libxputty: xadjustment.h File Reference
xadjustment.h File Reference
#include "xputty.h"
Data Structures
struct Adjustment_t
Adjustment_t - struct to hold a controller adjustment.
Macros
#define XADJUSTMENT_H_
Enumerations
enum CL_type {
CL_NONE = 0x0001, CL_CONTINUOS = 0x0002, CL_TOGGLE = 0x0004, CL_BUTTON = 0x0008,
CL_ENUM = 0x0016, CL_VIEWPORT = 0x0032, CL_METER = 0x0064, CL_LOGARITHMIC = 0x0128,
CL_LOGSCALE = 0x0256
}
CL_type - define the type of the controller adjustment one of this types must be given when set up a Adjustment_t for a Wdiget_t.
Functions
Adjustment_t * add_adjustment (Widget_t *w, float std_value, float value, float min_value, float max_value, float step, CL_type type)
*add_adjustment - adding a adjustment to a Widget_t
void set_adjustment (Adjustment_t *adj, float std_value, float value, float min_value, float max_value, float step, CL_type type)
*set_adjustment - set a new range to a existing Adjustment_t it will be created if it not exsits yet
void * delete_adjustment (Adjustment_t *adj)
delete_adjustment - freeing the memory of the Adjustment_t You usually don't need to call this, as it get handled by main_quit() -> destroy_widget()
float adj_get_state (Adjustment_t *adj)
adj_get_state - get the current state of the Adjustment_t
void adj_set_state (Adjustment_t *adj, float state)
adj_set_state - set the current state of the Adjustment_t
float adj_get_value (Adjustment_t *adj)
adj_get_value - get the current value of the Adjustment_t
void adj_set_value (Adjustment_t *adj, float value)
adj_set_value - set the current value to the Adjustment_t
void adj_set_start_value (void *w)
adj_set_start_value - internal use to store the value when pointer movment starts
void adj_set_scale (Adjustment_t *adj, float value)
adj_set_scale - internal use to scale the pointer movement (0.1 -1.0)
void adj_set_log_scale (Adjustment_t *adj, float value)
adj_set_log_scale - internal use to set the logarithmic scale
void adj_set_motion_state (void *w, float x, float y)
adj_set_motion_state - internal use to set value and state of the Adjustment_t on mouse pointer movment
void check_value_changed (Adjustment_t *adj, float *value)
check_value_changed - check if Adjustment_t value have changed and send value_changed_callback (VALUE_CHANGED) and adj_callback (ADJ_INTERN) if so
Macro Definition Documentation
XADJUSTMENT_H_
#define XADJUSTMENT_H_
Definition at line 24 of file xadjustment.h.
Enumeration Type Documentation
CL_type
enum CL_type
CL_type - define the type of the controller adjustment one of this types must be given when set up a Adjustment_t for a Wdiget_t.
Parameters
CL_NONE - Widget_t didn't request a adjustment
CL_CONTINUOS - Widget_t request a continuos adjustment
CL_TOGGLE - Widget_t request a toggle adjustment
CL_BUTTON - Widget_t request a button adjustment
CL_ENUM - Widget_t request a enum adjustment
CL_LOGARITHMIC - Widget_t request a logarithmic adjustment
Enumerator
CL_NONE
Widget_t didn't request a adjustment
CL_CONTINUOS
Widget_t request a continuos adjustment
CL_TOGGLE
Widget_t request a toggle adjustment
CL_BUTTON
Widget_t request a button adjustment
CL_ENUM
Widget_t request a enum adjustment
CL_VIEWPORT
Widget_t request a viewport adjustment
CL_METER
Widget_t request a viewport adjustment
CL_LOGARITHMIC
Widget_t request a logarithmic adjustment
CL_LOGSCALE
Widget_t request a logarithmic scaled adjustment
Definition at line 45 of file xadjustment.h.
              {
 /** Widget_t didn't request a adjustment */
     CL_NONE         = 0x0001,
 /** Widget_t request a continuos adjustment */
     CL_CONTINUOS    = 0x0002,
 /** Widget_t request a toggle adjustment */
     CL_TOGGLE       = 0x0004,
 /** Widget_t request a button adjustment */
     CL_BUTTON       = 0x0008,
 /** Widget_t request a enum adjustment */
     CL_ENUM         = 0x0016,
 /** Widget_t request a viewport adjustment */
     CL_VIEWPORT     = 0x0032,
 /** Widget_t request a viewport adjustment */
     CL_METER        = 0x0064,
 /** Widget_t request a logarithmic adjustment */
     CL_LOGARITHMIC  = 0x0128,
 /** Widget_t request a logarithmic scaled adjustment */
     CL_LOGSCALE     = 0x0256,
 }CL_type;
Function Documentation
add_adjustment()
Adjustment_t* add_adjustment (Widget_t * w, float std_value, float value, float min_value, float max_value, float step, CL_type type)
*add_adjustment - adding a adjustment to a Widget_t
Parameters
*w - pointer to the Widget_t request a Adjustment_t
std_value - standard value of the Adjustment_t
value - current value of the Adjustment_t
min_value - minimum value of the Adjustment_t
max_value - maximal value of the Adjustment_t
step - step to increase/decrease the Adjustment_t
type - set CL_type of Adjustment_t
Returns
*adj - pointer to the Adjustment_t
Definition at line 25 of file xadjustment.c.
{
     Adjustment_t *adj = (Adjustment_t*)malloc(sizeof(Adjustment_t));
     assert(adj);
     adj->log_scale = 20.0;
     switch(type) {
         case (CL_LOGSCALE) :
         *(adj) = (Adjustment_t) {
             .w           = w,
             .std_value   = powf(10,(std_value/adj->log_scale)),
             .value       = powf(10,(value/adj->log_scale)),
             .min_value   = powf(10,(min_value/adj->log_scale)),
             .max_value   = powf(10,(max_value/adj->log_scale)),
             .step        = step,
             .start_value = powf(10,(value/adj->log_scale)),
             .scale       = 1.0,
             .type        = type,
             .log_scale   = adj->log_scale
         };
         break;
         case (CL_LOGARITHMIC) :
         *(adj) = (Adjustment_t) {
             .w           = w,
             .std_value   = log10(std_value),
             .value       = log10(value),
             .min_value   = log10(min_value),
             .max_value   = log10(max_value),
             .step        = step,
             .start_value = log10(value),
             .scale       = 1.0,
             .type        = type,
             .log_scale   = adj->log_scale
         };
         break;
         default:
         *(adj) = (Adjustment_t) {
             .w           = w,
             .std_value   = std_value,
             .value       = value,
             .min_value   = min_value,
             .max_value   = max_value,
             .step        = step,
             .start_value = value,
             .scale       = 1.0,
             .type        = type,
             .log_scale   = adj->log_scale
         };
         break;
     }
     debug_print("Widget_t add adjustment\n");
     return adj;
 }
References CL_LOGARITHMIC, CL_LOGSCALE, debug_print, Adjustment_t::log_scale, and Widget_t::scale.
adj_get_state()
float adj_get_state (Adjustment_t * adj)
adj_get_state - get the current state of the Adjustment_t
Parameters
*adj - pointer to the Adjustment_t
Returns
float - return the Adjustment_t state mapped to (0<->1)
Definition at line 148 of file xadjustment.c.
{
     if (!adj) return 0.0;
     return (adj->value - adj->min_value) /
        (adj->max_value - adj->min_value);
 }
References Adjustment_t::max_value, Adjustment_t::min_value, and Adjustment_t::value.
adj_get_value()
float adj_get_value (Adjustment_t * adj)
adj_get_value - get the current value of the Adjustment_t
Parameters
*adj - pointer to the Adjustment_t
Returns
float - return the Adjustment_t value
Definition at line 154 of file xadjustment.c.
{
     if (!adj) return 0.0;
     if (adj->type == CL_LOGSCALE)
         return log10(adj->value)*adj->log_scale;
     else if (adj->type == CL_LOGARITHMIC)
         return powf(10,adj->value);
     return (adj->value);
 }
References CL_LOGARITHMIC, CL_LOGSCALE, Adjustment_t::log_scale, Adjustment_t::type, and Adjustment_t::value.
adj_set_log_scale()
void adj_set_log_scale (Adjustment_t * adj, float value)
adj_set_log_scale - internal use to set the logarithmic scale
Parameters
*adj - pointer to the Adjustment_t
value - value to set the scaleing factor to
Returns
void
Definition at line 183 of file xadjustment.c.
{
     adj->log_scale = value;
 }
References Adjustment_t::log_scale.
adj_set_motion_state()
void adj_set_motion_state (void * w, float x, float y)
adj_set_motion_state - internal use to set value and state of the Adjustment_t on mouse pointer movment
Parameters
*w - pointer to Widget_t containing Adjustment_t
x - movment on the x-axis
y - movement on the y-axis
Returns
void
Definition at line 187 of file xadjustment.c.
{
     Widget_t * wid = (Widget_t*)w;
     if(wid->adj_x) {
         float value= wid->adj_x->value;
         switch(wid->adj_x->type) {
             case (CL_LOGSCALE):
             case (CL_LOGARITHMIC):
             case (CL_CONTINUOS):
             {
                 float state = (wid->adj_x->start_value - wid->adj_x->min_value) /
                     (wid->adj_x->max_value - wid->adj_x->min_value);
                 float nsteps = wid->adj_x->step / (wid->adj_x->max_value - wid->adj_x->min_value);
                 float nvalue = min(1.0,max(0.0,state + ((float)(x - wid->pos_x)*wid->adj_x->scale *nsteps)));
                 float prevalue = nvalue * (wid->adj_x->max_value - wid->adj_x->min_value) + wid->adj_x->min_value;
                 float mulscale = round(prevalue/wid->adj_x->step);
                 value = min(wid->adj_x->max_value,max(wid->adj_x->min_value,mulscale*wid->adj_x->step));
             }
             break;
             case (CL_TOGGLE):
                 // dont toggle on motion!
                 // value = wid->adj_x->value ? 0.0 : 1.0;
             break;
             default:
             break;
         }
         check_value_changed(wid->adj_x, &value);
     }
     if(wid->adj_y) {
         float value = wid->adj_y->value;
         switch(wid->adj_y->type) {
             case (CL_LOGSCALE):
             case (CL_LOGARITHMIC):
             case (CL_CONTINUOS):
             {
                 float state = (wid->adj_y->start_value - wid->adj_y->min_value) /
                     (wid->adj_y->max_value - wid->adj_y->min_value);
                 float nsteps = wid->adj_y->step / (wid->adj_y->max_value - wid->adj_y->min_value);
                 float nvalue = min(1.0,max(0.0,state + ((float)(wid->pos_y - y)*wid->adj_y->scale *nsteps)));
                 float prevalue = nvalue * (wid->adj_y->max_value - wid->adj_y->min_value) + wid->adj_y->min_value;
                 float mulscale = round(prevalue/wid->adj_y->step);
                 value = min(wid->adj_y->max_value,max(wid->adj_y->min_value,mulscale*wid->adj_y->step));
             }
             break;
             case (CL_TOGGLE):
                 // dont toggle on motion!
                 // value = wid->adj_y->value ? 0.0 : 1.0;
             break;
             default:
             break;
         }
         check_value_changed(wid->adj_y, &value);
     }
 }
References Widget_t::adj_x, Widget_t::adj_y, check_value_changed(), CL_CONTINUOS, CL_LOGARITHMIC, CL_LOGSCALE, CL_TOGGLE, max, Adjustment_t::max_value, min, Adjustment_t::min_value, Widget_t::pos_x, Widget_t::pos_y, Adjustment_t::scale, Adjustment_t::start_value, Adjustment_t::step, Adjustment_t::type, and Adjustment_t::value.
adj_set_scale()
void adj_set_scale (Adjustment_t * adj, float value)
adj_set_scale - internal use to scale the pointer movement (0.1 -1.0)
Parameters
*adj - pointer to the Adjustment_t
value - value to set the scaleing factor to
Returns
void
Definition at line 179 of file xadjustment.c.
{
     adj->scale = value;
 }
References Adjustment_t::scale.
adj_set_start_value()
void adj_set_start_value (void * w)
adj_set_start_value - internal use to store the value when pointer movment starts
Parameters
*w - pointer to Widget_t containing the Adjustment_t
Returns
void
Definition at line 173 of file xadjustment.c.
{
     Widget_t * wid = (Widget_t*)w;
     if(wid->adj_x)wid->adj_x->start_value = wid->adj_x->value;
     if(wid->adj_y)wid->adj_y->start_value = wid->adj_y->value;
 }
References Widget_t::adj_x, Widget_t::adj_y, Adjustment_t::start_value, and Adjustment_t::value.
adj_set_state()
void adj_set_state (Adjustment_t * adj, float state)
adj_set_state - set the current state of the Adjustment_t
Parameters
*adj - pointer to the Adjustment_t
Returns
float - set the Adjustment_t state mapped to (0<->1)
Definition at line 141 of file xadjustment.c.
{
     if (!adj) return;
     float nvalue = min(1.0,max(0.0,state));
     float value = nvalue * (adj->max_value - adj->min_value) + adj->min_value;
     check_value_changed(adj, &value);
 }
References check_value_changed(), max, Adjustment_t::max_value, min, and Adjustment_t::min_value.
adj_set_value()
void adj_set_value (Adjustment_t * adj, float value)
adj_set_value - set the current value to the Adjustment_t
Parameters
*adj - pointer to the Adjustment_t
value - value to set the Adjustment_t to
Returns
void
Definition at line 163 of file xadjustment.c.
{
     if (!adj) return;
     if (adj->type == CL_LOGSCALE)
         v = powf(10,(v/adj->log_scale));
     else if (adj->type == CL_LOGARITHMIC)
         v = log10(v);
     v = min(adj->max_value,max(adj->min_value, v));
     check_value_changed(adj, &v);
 }
References check_value_changed(), CL_LOGARITHMIC, CL_LOGSCALE, Adjustment_t::log_scale, max, Adjustment_t::max_value, min, Adjustment_t::min_value, and Adjustment_t::type.
check_value_changed()
void check_value_changed (Adjustment_t * adj, float * value)
check_value_changed - check if Adjustment_t value have changed and send value_changed_callback (VALUE_CHANGED) and adj_callback (ADJ_INTERN) if so
Parameters
*adj - pointer to the Adjustment_t
value - value to check
Returns
void
Definition at line 241 of file xadjustment.c.
{
     debug_print("Adjustment_t check_value_changed %f\n", *(value));
     if(fabs(*(value) - adj->value)>=0.00001) {
         adj->value = *(value);
         adj->w->func.adj_callback(adj->w, NULL);
         adj->w->func.value_changed_callback(adj->w, value);
     }
 }
References Func_t::adj_callback, debug_print, Widget_t::func, Adjustment_t::value, Func_t::value_changed_callback, and Adjustment_t::w.
delete_adjustment()
void* delete_adjustment (Adjustment_t * adj)
delete_adjustment - freeing the memory of the Adjustment_t You usually don't need to call this, as it get handled by main_quit() -> destroy_widget()
Parameters
*adj - pointer to the Adjustment to free
Returns
*void
Definition at line 133 of file xadjustment.c.
{
     if(adj) {
         free(adj);
         debug_print("Widget_t delete adjustment\n");
     }
     return NULL;
 }
References debug_print.
set_adjustment()
void set_adjustment (Adjustment_t * adj, float std_value, float value, float min_value, float max_value, float step, CL_type type)
*set_adjustment - set a new range to a existing Adjustment_t it will be created if it not exsits yet
Parameters
*w - pointer to the Widget_t request a Adjustment_t
std_value - standard value of the Adjustment_t
value - current value of the Adjustment_t
min_value - minimum value of the Adjustment_t
max_value - maximal value of the Adjustment_t
step - step to increase/decrease the Adjustment_t
type - set CL_type of Adjustment_t
Returns
*adj - pointer to Adjustment_t
Definition at line 80 of file xadjustment.c.
{
     if (!adj) adj = (Adjustment_t*)malloc(sizeof(Adjustment_t));
     assert(adj);
     switch(type) {
         case (CL_LOGSCALE) :
         *(adj) = (Adjustment_t) {
             .w           = adj->w,
             .std_value   = powf(10,(std_value/adj->log_scale)),
             .value       = powf(10,(value/adj->log_scale)),
             .min_value   = powf(10,(min_value/adj->log_scale)),
             .max_value   = powf(10,(max_value/adj->log_scale)),
             .step        = step,
             .start_value = powf(10,(value/adj->log_scale)),
             .scale       = 1.0,
             .type        = type,
             .log_scale   = adj->log_scale
         };
         break;
         case (CL_LOGARITHMIC) :
         *(adj) = (Adjustment_t) {
             .w           = adj->w,
             .std_value   = log10(std_value),
             .value       = log10(value),
             .min_value   = log10(min_value),
             .max_value   = log10(max_value),
             .step        = step,
             .start_value = log10(value),
             .scale       = 1.0,
             .type        = type,
             .log_scale   = adj->log_scale
         };
         break;
         default:
         *(adj) = (Adjustment_t) {
             .w           = adj->w,
             .std_value   = std_value,
             .value       = value,
             .min_value   = min_value,
             .max_value   = max_value,
             .step        = step,
             .start_value = value,
             .scale       = 1.0,
             .type        = type,
             .log_scale   = adj->log_scale
         };
         break;
     }
     debug_print("Widget_t set adjustment\n");
 }
References CL_LOGARITHMIC, CL_LOGSCALE, debug_print, Adjustment_t::log_scale, Widget_t::scale, and Adjustment_t::w.