libxputty: xchildlist.h File Reference
xchildlist.h File Reference
#include "xputty.h"
Data Structures
struct Childlist_t
Childlist_t - struct to hold a Widget_t child list
Xputty main holds a list of any Widget_t created in relation to main
Any Event is only propagate to Widget_t's found in this list
Every Widget_t holds a list of Child Widget_t's they contain
When a Widget_t get destroy_widget() call, all of it's childs receive a destroy_widget() call before the Widget_t itself get destroyed
the expose_callback() (EXPOSE) and the configure_callback() (CONFIGURE) will be propagate to all childs in a Childlist_t.
Macros
#define XCHILDLIST_H_
Functions
void childlist_init (Childlist_t *childlist)
childlist_init - internal use to allocate the array to min size
You usually didn't need to call this
void childlist_destroy (Childlist_t *childlist)
childlist_destroy - internal use to free the Childlist_t
You usually didn't need to call this
void childlist_add_child (Childlist_t *childlist, Widget_t *child)
childlist_add_child - internal use to add a child to the Childlist_t
You usually didn't need to call this
void childlist_remove_child (Childlist_t *childlist, Widget_t *child)
childlist_remove_child - internal use to remove a child from the childlist
You usually didn't need to call this
int childlist_find_child (Childlist_t *childlist, Widget_t *child)
childlist_find_child - find a child in a the Childlist_t this could be sued to check if a Widget_t is a child of a other Widget_t
int childlist_find_widget (Childlist_t *childlist, Window child_window)
childlist_find_widget - find a child Widget_t in a the childlist by given the Window id
int childlist_has_child (Childlist_t *childlist)
childlist_has_child - check if a Widget_t Childlist_t contain a child
Macro Definition Documentation
XCHILDLIST_H_
#define XCHILDLIST_H_
Definition at line 24 of file xchildlist.h.
Function Documentation
childlist_add_child()
void childlist_add_child (Childlist_t * childlist, Widget_t * child)
childlist_add_child - internal use to add a child to the Childlist_t
You usually didn't need to call this
Parameters
*childlist - pointer to the Childlist_t
*child - pointer to the child to add
Returns
void
Definition at line 42 of file xchildlist.c.
{
     if(!childlist) childlist_init(childlist);
     if (childlist->cap < childlist->elem+2) {
          _childlist_add_elem(childlist);
      }
     childlist->childs[childlist->elem] = child;
     debug_print("Childlist_t  add_child\n");
     if (child->flags & IS_WINDOW) {
         Atom WM_DELETE_WINDOW;
         WM_DELETE_WINDOW = XInternAtom(child->app->dpy, "WM_DELETE_WINDOW", True);
         XSetWMProtocols(child->app->dpy, child->widget, &WM_DELETE_WINDOW, 1);
     }
     childlist->elem +=1;
 }
References _childlist_add_elem(), Widget_t::app, Childlist_t::cap, childlist_init(), Childlist_t::childs, debug_print, Xputty::dpy, Childlist_t::elem, Widget_t::flags, IS_WINDOW, and Widget_t::widget.
childlist_destroy()
void childlist_destroy (Childlist_t * childlist)
childlist_destroy - internal use to free the Childlist_t
You usually didn't need to call this
Parameters
*childlist - pointer to the Childlist_t
Returns
void
Definition at line 38 of file xchildlist.c.
{
     if(childlist) free(childlist->childs);
 }
References Childlist_t::childs.
childlist_find_child()
int childlist_find_child (Childlist_t * childlist, Widget_t * child)
childlist_find_child - find a child in a the Childlist_t this could be sued to check if a Widget_t is a child of a other Widget_t
Parameters
*childlist - pointer to the Childlist_t
*child - pointer to the child to find
Returns
int - return position in childlist or -1 when not found
Definition at line 71 of file xchildlist.c.
{
     int i = 0;
     for(;i<childlist->elem;i++) {
         if(childlist->childs[i] == child) {
             return i;
         }
     }
     return -1;
 }
References Childlist_t::childs, and Childlist_t::elem.
childlist_find_widget()
int childlist_find_widget (Childlist_t * childlist, Window child_window)
childlist_find_widget - find a child Widget_t in a the childlist by given the Window id
Parameters
*childlist - pointer to the Childlist_t
child_window - the Window to find the Widget_t for
Returns
int - return position in childlist or -1 when not found
Definition at line 81 of file xchildlist.c.
{
     int i = childlist->elem-1;
     for(;i>-1;i--) {
         if(childlist->childs[i]->widget == child_window) {
             return i;
         }
     }
     return -1;
 }
References Childlist_t::childs, Childlist_t::elem, and Widget_t::widget.
childlist_has_child()
int childlist_has_child (Childlist_t * childlist)
childlist_has_child - check if a Widget_t Childlist_t contain a child
Parameters
*childlist - pointer to the Childlist_t
Returns
int - return element counter value 0 when Widget_t Childlist_t didn't contain a child
Definition at line 91 of file xchildlist.c.
{
     return childlist->elem;
 }
References Childlist_t::elem.
childlist_init()
void childlist_init (Childlist_t * childlist)
childlist_init - internal use to allocate the array to min size
You usually didn't need to call this
Parameters
*childlist - pointer to the Childlist_t
Returns
void
Definition at line 25 of file xchildlist.c.
{
     childlist->childs = (Widget_t**)malloc(sizeof(Widget_t*) * 4);
     assert(childlist->childs != NULL);
     memset(childlist->childs, 0, 4 * sizeof(Widget_t*));
     childlist->cap =4;
     childlist->size = sizeof(childlist);
     childlist->elem = 0;
     int i = 0;
     for(;i<childlist->cap;i++) {
         childlist->childs[i] = NULL;
     }
 }
References Childlist_t::cap, Childlist_t::childs, Childlist_t::elem, and Childlist_t::size.
childlist_remove_child()
void childlist_remove_child (Childlist_t * childlist, Widget_t * child)
childlist_remove_child - internal use to remove a child from the childlist
You usually didn't need to call this
Parameters
*childlist - pointer to the Childlist_t
*child - pointer to the child to remove
Returns
void
Definition at line 57 of file xchildlist.c.
{
     if (!childlist) return;
     int it = childlist_find_child(childlist, child);
     if(it >= 0){
         childlist->childs[it] = NULL;
         childlist->elem--;
         int i = it;
         for(;i<childlist->elem;i++) {
             childlist->childs[i] = childlist->childs[i+1];
         }
         childlist->childs[childlist->elem+1] = NULL;
     }
 }
References childlist_find_child(), Childlist_t::childs, and Childlist_t::elem.