libxputty: xcombobox.h File Reference
xcombobox.h File Reference
#include "xputty.h"
#include "xmenu.h"
Macros
#define XCOMBOBOX_H_
Functions
Widget_t * add_combobox (Widget_t *parent, const char *label, int x, int y, int width, int height)
add_combobox - add a combobox
Widget_t * combobox_add_entry (Widget_t *wid, const char *label)
combobox_add_entry - add a entry to the combobox
void combobox_set_active_entry (Widget_t *w, int active)
combobox_set_active_entry - set the active combobox entry
Macro Definition Documentation
XCOMBOBOX_H_
#define XCOMBOBOX_H_
Definition at line 25 of file xcombobox.h.
Function Documentation
add_combobox()
Widget_t* add_combobox (Widget_t * parent, const char * label, int x, int y, int width, int height)
add_combobox - add a combobox
Parameters
*parent - pointer to the Widget_t request the button
x,y,width,height - the position/geometry to create the button
Returns
Widget_t* - pointer to the Widget_t button struct
Definition at line 32 of file xcombobox.c.
References _button_combobox_released(), _combobox_button_released(), _draw_combobox(), _draw_combobox_button(), _entry_released(), _set_entry(), add_adjustment(), add_button(), Widget_t::adj, Func_t::adj_callback, Widget_t::adj_y, Widget_t::app, Func_t::button_release_callback, CENTER, CL_ENUM, create_menu(), create_widget(), Func_t::enter_callback, Func_t::expose_callback, Widget_t::func, Resize_t::gravity, Widget_t::label, Func_t::leave_callback, Widget_t::scale, and transparent_draw().
{
     Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
     wid->label = label;
     wid->scale.gravity = CENTER;
     wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, -1.0,1.0, CL_ENUM);
     wid->adj = wid->adj_y;
     wid->func.adj_callback = _set_entry;
     wid->func.expose_callback = _draw_combobox;
     wid->func.enter_callback = transparent_draw;
     wid->func.leave_callback = transparent_draw;
     wid->func.button_release_callback = _combobox_button_released;
     Widget_t* button = add_button(wid, "", width-20, 0, 20, height);
     button->func.expose_callback = _draw_combobox_button;
     button->func.button_release_callback = _button_combobox_released;
     Widget_t* menu = create_menu(wid, 25);
     menu->func.button_release_callback = _entry_released;
     return wid;
 }
combobox_add_entry()
Widget_t* combobox_add_entry (Widget_t * wid, const char * label)
combobox_add_entry - add a entry to the combobox
Parameters
*wid - pointer to the Widget_t combobox
*label - Label to show on the menu
Returns
Widget_t* - pointer to the Widget_t menu_item struct
Definition at line 56 of file xcombobox.c.
References Widget_t::adj, Widget_t::childlist, Childlist_t::childs, CL_ENUM, Widget_t::label, Adjustment_t::max_value, menu_add_item(), and set_adjustment().
{
     Widget_t *menu = wid->childlist->childs[1];
     Widget_t *item = menu_add_item(menu,label);
     wid->label = label;
     float max_value = wid->adj->max_value+1.0;
     set_adjustment(wid->adj,0.0, max_value, 0.0, max_value,1.0, CL_ENUM);
     return item;
 }
combobox_set_active_entry()
void combobox_set_active_entry (Widget_t * w, int active)
combobox_set_active_entry - set the active combobox entry
Parameters
*w_ - void pointer to the Widget_t combobox
active - the active entry (int)
Returns
void
Definition at line 25 of file xcombobox.c.
References Widget_t::adj, adj_set_value(), Adjustment_t::max_value, and Adjustment_t::min_value.
{
     float value = (float)active;
     if (value>w->adj->max_value) value = w->adj->max_value;
     else if (value<w->adj->min_value) value = w->adj->min_value;
     adj_set_value(w->adj, value);
 }