libxputty: xknob_private.h File Reference
xknob_private.h File Reference
#include "xknob.h"
Macros
#define XKNOB_PRIVATE_H_
Functions
void _draw_image_knob (Widget_t *w, int width_t, int height_t)
_draw_image_knob - internal draw the knob from image to the buffer
void _draw_knob (void *w_, void *user_data)
_draw_knob - internal draw the knob to the buffer
void _knob_released (void *w_, void *button_, void *user_data)
_knob_released - redraw the slider when buttob released
Macro Definition Documentation
XKNOB_PRIVATE_H_
#define XKNOB_PRIVATE_H_
Definition at line 25 of file xknob_private.h.
Function Documentation
_draw_image_knob()
void _draw_image_knob (Widget_t * w, int width_t, int height_t)
_draw_image_knob - internal draw the knob from image to the buffer
Parameters
*w - pointer to the Widget_t knob
Returns
void
Definition at line 25 of file xknob_private.c.
References adj_get_state(), Widget_t::adj_y, Widget_t::crb, and Widget_t::image.
{
     int width = cairo_xlib_surface_get_width(w->image);
     int height = cairo_xlib_surface_get_height(w->image);
     double x = (double)width_t/(double)height;
     double y = (double)height/(double)width_t;
     double knobstate = adj_get_state(w->adj_y);
     int findex = (int)(((width/height)-1) * knobstate);
     cairo_scale(w->crb, x,x);
     //widget_set_scale(w);
     cairo_set_source_surface (w->crb, w->image, -height*findex, 0);
     cairo_rectangle(w->crb,0, 0, height, height);
     cairo_fill(w->crb);
     //widget_reset_scale(w);
     cairo_scale(w->crb, y,y);
 }
_draw_knob()
void _draw_knob (void * w_, void * user_data)
_draw_knob - internal draw the knob to the buffer
Parameters
*w_ - void pointer to the Widget_t button
*user_data - void pointer to attached user_data
Returns
void
get values for the knob
create a rotating pointer on the kob
show value on the kob
show label below the knob
Definition at line 41 of file xknob_private.c.
References _draw_image_knob(), adj_get_state(), Widget_t::adj_y, Widget_t::app, Widget_t::crb, Xputty::dpy, get_color_state(), Widget_t::image, Widget_t::label, min, NORMAL_, Widget_t::state, use_bg_color_scheme(), use_fg_color_scheme(), use_shadow_color_scheme(), use_text_color_scheme(), Adjustment_t::value, and Widget_t::widget.
{
     Widget_t *w = (Widget_t*)w_;
     XWindowAttributes attrs;
     XGetWindowAttributes(w->app->dpy, (Window)w->widget, &attrs);
     int width = attrs.width-2;
     int height = attrs.height-2;
     const double scale_zero = 20 * (M_PI/180); // defines "dead zone" for knobs
     int arc_offset = 0;
     int knob_x = 0;
     int knob_y = 0;
     int grow = (width > height) ? height:width;
     knob_x = grow-1;
     knob_y = grow-1;
     /** get values for the knob **/
     int knobx = (width - knob_x) * 0.5;
     int knobx1 = width* 0.5;
     int knoby = (height - knob_y) * 0.5;
     int knoby1 = height * 0.5;
     if (w->image) {
         _draw_image_knob(w, width, height);
     } else {
         double knobstate = adj_get_state(w->adj_y);
         double angle = scale_zero + knobstate * 2 * (M_PI - scale_zero);
         double pointer_off =knob_x/6;
         double radius = min(knob_x-pointer_off, knob_y-pointer_off) / 2;
         double lengh_x = (knobx+radius+pointer_off/2) - radius * sin(angle);
         double lengh_y = (knoby+radius+pointer_off/2) + radius * cos(angle);
         double radius_x = (knobx+radius+pointer_off/2) - radius/ 1.18 * sin(angle);
         double radius_y = (knoby+radius+pointer_off/2) + radius/ 1.18 * cos(angle);
         cairo_arc(w->crb,knobx1+arc_offset, knoby1+arc_offset, knob_x/2.1, 0, 2 * M_PI );
         use_shadow_color_scheme(w, get_color_state(w));
         cairo_fill (w->crb);
         cairo_new_path (w->crb);
         use_bg_color_scheme(w, get_color_state(w));
         cairo_arc(w->crb,knobx1+arc_offset, knoby1+arc_offset, knob_x/3.1, 0, 2 * M_PI );
         cairo_fill_preserve(w->crb);
         use_fg_color_scheme(w, NORMAL_);
         cairo_set_line_width(w->crb, knobx1/15);
         cairo_stroke(w->crb);
         cairo_new_path (w->crb);
         /** create a rotating pointer on the kob**/
         cairo_set_line_cap(w->crb, CAIRO_LINE_CAP_ROUND);
         cairo_set_line_join(w->crb, CAIRO_LINE_JOIN_BEVEL);
         cairo_move_to(w->crb, radius_x, radius_y);
         cairo_line_to(w->crb,lengh_x,lengh_y);
         cairo_set_line_width(w->crb,knobx1/7);
         use_fg_color_scheme(w, NORMAL_);
         cairo_stroke(w->crb);
         cairo_new_path (w->crb);
     }
     cairo_text_extents_t extents;
     /** show value on the kob**/
     if (w->state) {
         char s[64];
         const char* format[] = {"%.1f", "%.2f", "%.3f"};
         if (fabs(w->adj_y->value)>9.99) {
             snprintf(s, 63,"%d",  (int) w->adj_y->value);
         } else if (fabs(w->adj_y->value)>0.99) {
             snprintf(s, 63, format[1-1], w->adj_y->value);
         } else {
             snprintf(s, 63, format[2-1], w->adj_y->value);
         }
         cairo_set_source_rgb (w->crb, 0.6, 0.6, 0.6);
         cairo_set_font_size (w->crb, knobx1/4);
         cairo_select_font_face (w->crb, "Sans", CAIRO_FONT_SLANT_NORMAL,
                                    CAIRO_FONT_WEIGHT_BOLD);
         cairo_text_extents(w->crb, s, &extents);
         cairo_move_to (w->crb, knobx1-extents.width/2, knoby1+extents.height/2);
         cairo_show_text(w->crb, s);
         cairo_new_path (w->crb);
     }
     /** show label below the knob**/
     use_text_color_scheme(w, get_color_state(w));
     float font_size = ((height/2.2 < (width*0.5)/3) ? height/2.2 : (width*0.5)/3);
     cairo_set_font_size (w->crb, font_size);
     cairo_select_font_face (w->crb, "Sans", CAIRO_FONT_SLANT_NORMAL,
                                CAIRO_FONT_WEIGHT_BOLD);
     cairo_text_extents(w->crb,w->label , &extents);
     cairo_move_to (w->crb, knobx1-extents.width/2, height );
     cairo_show_text(w->crb, w->label);
     cairo_new_path (w->crb);
 }
_knob_released()
void _knob_released (void * w_, void * button_, void * user_data)
_knob_released - redraw the slider when buttob released
Parameters
*w_ - void pointer to the Widget_t button
*user_data - void pointer to attached user_data
Returns
void
Definition at line 136 of file xknob_private.c.
References expose_widget(), Widget_t::flags, HAS_POINTER, and Widget_t::state.
{
     Widget_t *w = (Widget_t*)w_;
     if (w->flags & HAS_POINTER) w->state= 1;
     expose_widget(w_);
 }