libxputty: xlistbox.h File Reference
xlistbox.h File Reference
#include "xputty.h"
Macros
#define XLISTBOX_H_
Functions
void listbox_set_active_entry (Widget_t *w, int active)
listbox_set_active_entry - set the active listbox entry
Widget_t * create_listbox_viewport (Widget_t *parent, int elem, int width, int height)
create_listbox_viewport - create a viewport on a listbox to a Widget_t
Widget_t * add_listbox (Widget_t *parent, const char *label, int x, int y, int width, int height)
add_label - add a listbox to a Widget_t
Widget_t * listbox_add_entry (Widget_t *listbox, const char *label)
listbox_add_entry - add a item to listbox
Macro Definition Documentation
XLISTBOX_H_
#define XLISTBOX_H_
Definition at line 25 of file xlistbox.h.
Function Documentation
add_listbox()
Widget_t* add_listbox (Widget_t * parent, const char * label, int x, int y, int width, int height)
add_label - add a listbox to a Widget_t
Parameters
*parent - pointer to the Widget_t request the label
*label - Label to show on the button
x,y,width,height - the position/geometry to create the label
Returns
Widget_t* - pointer to the Widget_t label struct
Definition at line 46 of file xlistbox.c.
References _draw_listbox(), add_adjustment(), Widget_t::adj, Widget_t::adj_y, Widget_t::app, CENTER, CL_NONE, create_listbox_viewport(), create_widget(), Func_t::expose_callback, Widget_t::func, Resize_t::gravity, Widget_t::label, and Widget_t::scale.
{
     Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
     wid->label = label;
     wid->scale.gravity = CENTER;
     wid->func.expose_callback = _draw_listbox;
     int elem = height/25;
     wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, -1.0,1.0, CL_NONE);
     wid->adj = wid->adj_y;
     create_listbox_viewport(wid, elem, width, height);
     return wid;
 }
create_listbox_viewport()
Widget_t* create_listbox_viewport (Widget_t * parent, int elem, int width, int height)
create_listbox_viewport - create a viewport on a listbox to a Widget_t
Parameters
*parent - pointer to the Widget_t the listbox should pop over
width - define the width of the viewport
height - define the height of the viewport
Returns
Widget_t* - pointer to the Widget_t viewport
Definition at line 33 of file xlistbox.c.
References _configure_listbox(), _draw_listbox_viewslider(), _reconfigure_listbox_viewport(), _set_listbox_viewpoint(), add_adjustment(), Widget_t::adj, Func_t::adj_callback, Widget_t::adj_y, Widget_t::app, CL_VIEWPORT, Func_t::configure_notify_callback, create_widget(), Func_t::expose_callback, Widget_t::func, Resize_t::gravity, Func_t::map_notify_callback, NORTHEAST, and Widget_t::scale.
{
     Widget_t *wid = create_widget(parent->app, parent, 0, 0, width, height);
     wid->scale.gravity = NORTHEAST;
     float max_value = -elem ;
     wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, max_value,1.0, CL_VIEWPORT);
     wid->adj = wid->adj_y;
     wid->func.adj_callback = _set_listbox_viewpoint;
     wid->func.expose_callback = _draw_listbox_viewslider;
     wid->func.configure_notify_callback = _reconfigure_listbox_viewport;
     wid->func.map_notify_callback = _configure_listbox;
     return wid;
 }
listbox_add_entry()
Widget_t* listbox_add_entry (Widget_t * listbox, const char * label)
listbox_add_entry - add a item to listbox
Parameters
*listbox - pointer to the Widget_t listbox
*label - Label to show on the listbox
Returns
Widget_t* - pointer to the Widget_t listbox_item struct
Definition at line 60 of file xlistbox.c.
References _draw_listbox_item(), _listbox_entry_released(), Widget_t::adj, Widget_t::app, Func_t::button_release_callback, Widget_t::childlist, childlist_has_child(), Childlist_t::childs, CL_NONE, CL_VIEWPORT, create_widget(), Func_t::enter_callback, Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, HAS_TOOLTIP, Resize_t::init_width, Widget_t::label, Func_t::leave_callback, Adjustment_t::max_value, MENUITEM, Widget_t::scale, set_adjustment(), transparent_draw(), and USE_TRANSPARENCY.
{
     Widget_t* view_port =  listbox->childlist->childs[0];
     int width = listbox->scale.init_width;
     int si = childlist_has_child(view_port->childlist);
     Widget_t *wid = create_widget(listbox->app, view_port, 0, 25*si, width, 25);
     float max_value = view_port->adj->max_value+1.0;
     set_adjustment(view_port->adj,0.0, 0.0, 0.0, max_value,1.0, CL_VIEWPORT);
     max_value = listbox->adj->max_value+1.0;
     set_adjustment(listbox->adj,0.0, 0.0, 0.0, max_value,1.0, CL_NONE);
     wid->flags &= ~USE_TRANSPARENCY | ~HAS_TOOLTIP;
     wid->scale.gravity = MENUITEM;
     wid->label = label;
     wid->func.expose_callback = _draw_listbox_item;
     wid->func.enter_callback = transparent_draw;
     wid->func.leave_callback = transparent_draw;
     wid->func.button_release_callback = _listbox_entry_released;
     return wid;
 }
listbox_set_active_entry()
void listbox_set_active_entry (Widget_t * w, int active)
listbox_set_active_entry - set the active listbox entry
Parameters
*w_ - void pointer to the Widget_t listbox
active - the active entry (int)
Returns
void
Definition at line 26 of file xlistbox.c.
References Widget_t::adj, adj_set_value(), Adjustment_t::max_value, and Adjustment_t::min_value.
{
     float value = (float)active;
     if (value>w->adj->max_value) value = w->adj->max_value;
     else if (value<w->adj->min_value) value = w->adj->min_value;
     adj_set_value(w->adj, value);
 }