libxputty: xmenu.h File Reference
xmenu.h File Reference
#include "xputty.h"
Macros
#define XMENU_H_
Functions
void pop_menu_show (Widget_t *parent, Widget_t *menu, int elem, bool above)
pop_menu_show - pop up a menu to a Widget_t
Widget_t * create_viewport (Widget_t *parent, int width, int height)
create_viewport - create a viewport on a menu to a Widget_t
Widget_t * add_menu (Widget_t *parent, const char *label, int x, int y, int width, int height)
add_menu - add a menu to a Widget_t
Widget_t * menu_add_entry (Widget_t *wid, const char *label)
menu_add_entry - add a entry to menu
Widget_t * menu_add_radio_entry (Widget_t *wid, const char *label)
menu_add_radio_entry- add a radio entry to menu
Widget_t * create_menu (Widget_t *parent, int height)
create_menu - create a menu to a Widget_t
Widget_t * menu_add_item (Widget_t *menu, const char *label)
menu_add_item - add a item to menu
Widget_t * menu_add_accel_item (Widget_t *menu, const char *label)
menu_add_accel_item - add a accel item to menu
Widget_t * menu_add_check_item (Widget_t *menu, const char *label)
menu_add_check_item - add a item to menu
void radio_item_set_active (Widget_t *w)
radio_item_set_active - activate selected radio item
Widget_t * menu_add_radio_item (Widget_t *menu, const char *label)
menu_add_radio_item - add a radio item to menu
void menu_add_numeric_items (Widget_t *menu, int *imin, int *imax)
menu_add_numeric_items - add numeric items from imin to imax to menu
Macro Definition Documentation
XMENU_H_
#define XMENU_H_
Definition at line 24 of file xmenu.h.
Function Documentation
add_menu()
Widget_t* add_menu (Widget_t * parent, const char * label, int x, int y, int width, int height)
add_menu - add a menu to a Widget_t
Parameters
*parent - pointer to the Widget_t the menu should pop over
*label - the label of the menu
x,y,width,height - the position/geometry to create the menu
Returns
Widget_t* - pointer to the Widget_t button struct
Definition at line 69 of file xmenu.c.
{
     Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
     wid->label = label;
     wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, -1.0,1.0, CL_NONE);
     wid->adj = wid->adj_y;
     wid->scale.gravity = NONE;
     wid->state = 0;
     wid->func.adj_callback = set_active_radio_entry;
     wid->func.expose_callback = _draw_menu_label;
     wid->func.enter_callback = _check_menu_state;
     wid->func.leave_callback = transparent_draw;
     wid->func.button_release_callback = _menu_released;
     Widget_t* menu = create_menu(wid, 25);
     menu->func.button_release_callback = _menu_entry_released;
     return wid;
 }
References _check_menu_state(), _draw_menu_label(), _menu_entry_released(), _menu_released(), add_adjustment(), Widget_t::adj, Func_t::adj_callback, Widget_t::adj_y, Widget_t::app, Func_t::button_release_callback, CL_NONE, create_menu(), create_widget(), Func_t::enter_callback, Func_t::expose_callback, Widget_t::func, Resize_t::gravity, Widget_t::label, Func_t::leave_callback, NONE, Widget_t::scale, set_active_radio_entry(), Widget_t::state, and transparent_draw().
create_menu()
Widget_t* create_menu (Widget_t * parent, int height)
create_menu - create a menu to a Widget_t
Parameters
*parent - pointer to the Widget_t the menu should pop over
height - define the height of a single menu item
Returns
Widget_t* - pointer to the Widget_t button struct
Definition at line 107 of file xmenu.c.
{
     int x1, y1;
     Window child;
     XTranslateCoordinates( parent->app->dpy, parent->widget, DefaultRootWindow(parent->app->dpy), 0, 0, &x1, &y1, &child );
     Widget_t *wid = create_window(parent->app, DefaultRootWindow(parent->app->dpy), x1, y1, 10, height);
     create_viewport(wid, 10, 5*height);
     XSetWindowAttributes attributes;
     attributes.override_redirect = True;
     XChangeWindowAttributes(parent->app->dpy, wid->widget, CWOverrideRedirect, &attributes);
     Atom window_type = XInternAtom(wid->app->dpy, "_NET_WM_WINDOW_TYPE", False);
     Atom window_type_popup = XInternAtom(wid->app->dpy, "_NET_WM_WINDOW_TYPE_DROPDOWN_MENU", False);
     XChangeProperty(wid->app->dpy, wid->widget, window_type,
         XA_ATOM, 32, PropModeReplace, (unsigned char *) &window_type_popup,1 );
     Atom window_state = XInternAtom(wid->app->dpy, "_NET_WM_STATE", False);
     Atom window_state_modal = XInternAtom(wid->app->dpy, "_NET_WM_STATE_MODAL", False);
     XChangeProperty(wid->app->dpy, wid->widget, window_state,
         XA_ATOM, 32, PropModeReplace, (unsigned char *) &window_state_modal, 1);
     XSetTransientForHint(parent->app->dpy,wid->widget,parent->widget);
     wid->func.expose_callback = _draw_menu;
     wid->flags |= IS_POPUP;
     wid->scale.gravity = NONE;
     childlist_add_child(parent->childlist, wid);
     return wid;
 }
References _draw_menu(), Widget_t::app, Widget_t::childlist, childlist_add_child(), create_viewport(), create_window(), Xputty::dpy, Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, IS_POPUP, NONE, Widget_t::scale, and Widget_t::widget.
create_viewport()
Widget_t* create_viewport (Widget_t * parent, int width, int height)
create_viewport - create a viewport on a menu to a Widget_t
Parameters
*parent - pointer to the Widget_t the menu should pop over
width - define the width of the viewport
height - define the height of the viewport
Returns
Widget_t* - pointer to the Widget_t viewport
Definition at line 40 of file xmenu.c.
{
     Widget_t *wid = create_widget(parent->app, parent, 0, 0, width, height);
     wid->scale.gravity = NONE;
     wid->flags &= ~USE_TRANSPARENCY;
     wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, -1.0,1.0, CL_VIEWPORT);
     wid->adj = wid->adj_y;
     wid->func.adj_callback = _set_viewpoint;
     wid->func.expose_callback = _draw_viewslider;
     return wid;
 }
References _draw_viewslider(), _set_viewpoint(), add_adjustment(), Widget_t::adj, Func_t::adj_callback, Widget_t::adj_y, Widget_t::app, CL_VIEWPORT, create_widget(), Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, NONE, Widget_t::scale, and USE_TRANSPARENCY.
menu_add_accel_item()
Widget_t* menu_add_accel_item (Widget_t * menu, const char * label)
menu_add_accel_item - add a accel item to menu
Parameters
*menu - pointer to the Widget_t menu
*label - Label to show on the menu
Returns
Widget_t* - pointer to the Widget_t menu_item struct
Definition at line 156 of file xmenu.c.
{
     Widget_t *wid = menu_add_item(menu, label);
     wid->func.expose_callback = _draw_accel_item;
     return wid;
 }
References _draw_accel_item(), Func_t::expose_callback, Widget_t::func, and menu_add_item().
menu_add_check_item()
Widget_t* menu_add_check_item (Widget_t * menu, const char * label)
menu_add_check_item - add a item to menu
Parameters
*menu - pointer to the Widget_t menu
*label - Label to show on the menu
Returns
Widget_t* - pointer to the Widget_t menu_item struct
Definition at line 162 of file xmenu.c.
{
     Widget_t *wid = menu_add_item(menu, label);
     wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, 1.0,1.0, CL_TOGGLE);
     wid->adj = wid->adj_y;
     wid->func.expose_callback = _draw_check_item;
     wid->func.button_press_callback = _check_item_button_pressed;
     return wid;
 }
References _check_item_button_pressed(), _draw_check_item(), add_adjustment(), Widget_t::adj, Widget_t::adj_y, Func_t::button_press_callback, CL_TOGGLE, Func_t::expose_callback, Widget_t::func, and menu_add_item().
menu_add_entry()
Widget_t* menu_add_entry (Widget_t * wid, const char * label)
menu_add_entry - add a entry to menu
Parameters
*wid - pointer to the Widget_t menu
*label - Label to show on the menu
Returns
Widget_t* - pointer to the Widget_t menu_item struct
Definition at line 89 of file xmenu.c.
{
     Widget_t *menu = wid->childlist->childs[0];
     Widget_t *item = menu_add_accel_item(menu,label);
     float max_value = wid->adj->max_value+1.0;
     set_adjustment(wid->adj,0.0, max_value, 0.0, max_value,1.0, CL_NONE);
     return item;
 }
References Widget_t::adj, Widget_t::childlist, Childlist_t::childs, CL_NONE, Adjustment_t::max_value, menu_add_accel_item(), and set_adjustment().
menu_add_item()
Widget_t* menu_add_item (Widget_t * menu, const char * label)
menu_add_item - add a item to menu
Parameters
*menu - pointer to the Widget_t menu
*label - Label to show on the menu
Returns
Widget_t* - pointer to the Widget_t menu_item struct
Definition at line 137 of file xmenu.c.
{
     Widget_t* view_port =  menu->childlist->childs[0];
     XWindowAttributes attrs;
     XGetWindowAttributes(menu->app->dpy, (Window)menu->widget, &attrs);
     int width = attrs.width;
     int height = attrs.height;
     int si = childlist_has_child(view_port->childlist);
     Widget_t *wid = create_widget(menu->app, view_port, 0, height*si, width, height);
     float max_value = view_port->adj->max_value+1.0;
     set_adjustment(view_port->adj,0.0, 0.0, 0.0, max_value,1.0, CL_VIEWPORT);
     wid->scale.gravity = MENUITEM;
     wid->flags &= ~USE_TRANSPARENCY;
     wid->label = label;
     wid->func.expose_callback = _draw_item;
     wid->func.enter_callback = transparent_draw;
     wid->func.leave_callback = transparent_draw;
     return wid;
 }
References _draw_item(), Widget_t::adj, Widget_t::app, Widget_t::childlist, childlist_has_child(), Childlist_t::childs, CL_VIEWPORT, create_widget(), Xputty::dpy, Func_t::enter_callback, Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, Widget_t::label, Func_t::leave_callback, Adjustment_t::max_value, MENUITEM, Widget_t::scale, set_adjustment(), transparent_draw(), USE_TRANSPARENCY, and Widget_t::widget.
menu_add_numeric_items()
void menu_add_numeric_items (Widget_t * menu, int * imin, int * imax)
menu_add_numeric_items - add numeric items from imin to imax to menu
Parameters
*menu - pointer to the Widget_t menu
*imin - the low number of the numeric items
*imax - the high number of the numeric items
Returns
void
Definition at line 193 of file xmenu.c.
{
     Widget_t* view_port =  menu->childlist->childs[0];
     XWindowAttributes attrs;
     XGetWindowAttributes(menu->app->dpy, (Window)menu->widget, &attrs);
     int width = attrs.width;
     int height = attrs.height;
     int si = childlist_has_child(view_port->childlist);
     float max_value = view_port->adj->max_value;
     Widget_t *wid;
     int i = (*imin);
     int o = (*imax)+1;
     for (;i<o;i++) {
         si = childlist_has_child(view_port->childlist);
         wid = create_widget(menu->app, view_port, 0, height*si, width, height);
         max_value += 1.0;
         set_adjustment(view_port->adj,0.0, 0.0, 0.0, max_value,1.0, CL_VIEWPORT);
         wid->scale.gravity = MENUITEM;
         wid->flags &= ~USE_TRANSPARENCY;
         snprintf(wid->input_label, 31, "%i",i);
         wid->label = wid->input_label;
         wid->func.expose_callback = _draw_item;
         wid->func.enter_callback = transparent_draw;
         wid->func.leave_callback = transparent_draw;
     }
 }
References _draw_item(), Widget_t::adj, Widget_t::app, Widget_t::childlist, childlist_has_child(), Childlist_t::childs, CL_VIEWPORT, create_widget(), Xputty::dpy, Func_t::enter_callback, Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, Widget_t::input_label, Widget_t::label, Func_t::leave_callback, Adjustment_t::max_value, MENUITEM, Widget_t::scale, set_adjustment(), transparent_draw(), USE_TRANSPARENCY, and Widget_t::widget.
menu_add_radio_entry()
Widget_t* menu_add_radio_entry (Widget_t * wid, const char * label)
menu_add_radio_entry- add a radio entry to menu
Parameters
*wid - pointer to the Widget_t menu
*label - Label to show on the menu
Returns
Widget_t* - pointer to the Widget_t menu_item struct
Definition at line 98 of file xmenu.c.
{
     Widget_t *menu = wid->childlist->childs[0];
     Widget_t *item = menu_add_radio_item(menu,label);
     float max_value = wid->adj->max_value+1.0;
     set_adjustment(wid->adj,0.0, max_value, 0.0, max_value,1.0, CL_NONE);
     return item;
 }
References Widget_t::adj, Widget_t::childlist, Childlist_t::childs, CL_NONE, Adjustment_t::max_value, menu_add_radio_item(), and set_adjustment().
menu_add_radio_item()
Widget_t* menu_add_radio_item (Widget_t * menu, const char * label)
menu_add_radio_item - add a radio item to menu
Parameters
*menu - pointer to the Widget_t menu
*label - Label to show on the menu
Returns
Widget_t* - pointer to the Widget_t menu_item struct
Definition at line 183 of file xmenu.c.
{
     Widget_t *wid = menu_add_check_item(menu, label);
     wid->flags |= IS_RADIO;
     wid->func.expose_callback = _draw_check_item;
     wid->func.button_press_callback = _radio_item_button_pressed;
     radio_item_set_active(wid);
     return wid;
 }
References _draw_check_item(), _radio_item_button_pressed(), Func_t::button_press_callback, Func_t::expose_callback, Widget_t::flags, Widget_t::func, IS_RADIO, menu_add_check_item(), and radio_item_set_active().
pop_menu_show()
void pop_menu_show (Widget_t * parent, Widget_t * menu, int elem, bool above)
pop_menu_show - pop up a menu to a Widget_t
Parameters
*parent - pointer to the Widget_t the menu should pop over
*menu - the menu to show
Returns
void
Definition at line 26 of file xmenu.c.
{
     if (!childlist_has_child(menu->childlist)) return;
     Widget_t* view_port =  menu->childlist->childs[0];
     if (!view_port->childlist->elem) return;
     _configure_menu(parent, menu, elem, above);
     pop_widget_show_all(menu);
     int err = XGrabPointer(menu->app->dpy, DefaultRootWindow(parent->app->dpy), True,
                  ButtonPressMask|ButtonReleaseMask|PointerMotionMask,
                  GrabModeAsync, GrabModeAsync, None, None, CurrentTime);
     menu->app->hold_grab = menu;
     if (err) debug_print("Error grap pointer\n");
 }
References _configure_menu(), Widget_t::app, Widget_t::childlist, childlist_has_child(), Childlist_t::childs, debug_print, Xputty::dpy, Childlist_t::elem, Xputty::hold_grab, and pop_widget_show_all().
radio_item_set_active()
void radio_item_set_active (Widget_t * w)
radio_item_set_active - activate selected radio item
Parameters
*w - the Widget_t to activate
Returns
void
Definition at line 171 of file xmenu.c.
{
     Widget_t * p = (Widget_t*) w->parent;
     int i = p->childlist->elem-1;
     for(;i>-1;i--) {
         Widget_t *wid = p->childlist->childs[i];
         if (wid->adj && wid->flags & IS_RADIO) {
             if (wid == w) adj_set_value(wid->adj_y, 1.0);
             else adj_set_value(wid->adj_y, 0.0);
         }
     }
 }
References Widget_t::adj, adj_set_value(), Widget_t::adj_y, Widget_t::childlist, Childlist_t::childs, Childlist_t::elem, Widget_t::flags, IS_RADIO, and Widget_t::parent.