libxputty: xmenu_private.c File Reference
xmenu_private.c File Reference
#include "xmenu_private.h"
Functions
int _menu_remove_low_dash (char *str)
void _draw_menu_label (void *w_, void *user_data)
_draw_menu_label - draw the menu label on expose call
void _check_menu_state (void *w_, void *user_data)
_check_menu_state - follow the mouse pointer when a menu is active
void _menu_released (void *w_, void *button_, void *user_data)
_menu_released - popup the menu on click
void _menu_entry_released (void *w_, void *item_, void *user_data)
_menu_entry_released - the menu release func
void _draw_menu (void *w_, void *user_data)
_draw_menu - draw menu on expose call
void _draw_item (void *w_, void *user_data)
_draw_item - draw item on expose call
void _draw_accel_item (void *w_, void *user_data)
_draw_accel_item - draw accel item on expose call
void _draw_check_item (void *w_, void *user_data)
_draw_check_item - draw item on expose call
void _draw_viewslider (void *w_, void *user_data)
_draw_viewslider - draw a slider on the viewport to indicate the view point
void _set_viewpoint (void *w_, void *user_data)
_set_viewpoint - move the view_port to position
void _check_item_button_pressed (void *w_, void *button_, void *user_data)
_check_item_button_pressed - redraw item on button press
void _radio_item_button_pressed (void *w_, void *button_, void *user_data)
_radio_item_button_pressed - redraw item on button press
void _configure_menu (Widget_t *parent, Widget_t *menu, int elem, bool above)
_configure_menu - set final size and position of menu to a Widget_t
Function Documentation
_check_item_button_pressed()
void _check_item_button_pressed (void * w_, void * button_, void * user_data)
_check_item_button_pressed - redraw item on button press
Parameters
*button - the xbutton which is pressed
*user_data - attached user_data
Returns
void
Definition at line 266 of file xmenu_private.c.
{
     Widget_t *w = (Widget_t*)w_;
     if (w->flags & HAS_FOCUS) {
         float value = w->adj_y->value ? 0.0 : 1.0;
         adj_set_value(w->adj_y, value);
     }
 }
References adj_set_value(), Widget_t::adj_y, Widget_t::flags, HAS_FOCUS, and Adjustment_t::value.
_check_menu_state()
void _check_menu_state (void * w_, void * user_data)
_check_menu_state - follow the mouse pointer when a menu is active
Parameters
*w_ - the menu to check
*user_data - attached user_data
Returns
void
Definition at line 78 of file xmenu_private.c.
{
     Widget_t *w = (Widget_t*)w_;
     Widget_t *parent = w->parent;
     int i = parent->childlist->elem-1;
     for(;i>-1;i--) {
         Widget_t *wid = parent->childlist->childs[i];
         if (childlist_has_child(wid->childlist)) {
             if ((wid->childlist->childs[0] == w->app->hold_grab) && (wid !=w)) {
                 XUngrabPointer(w->app->dpy,CurrentTime);
                 widget_hide(w->app->hold_grab);
                 w->app->hold_grab = NULL;
                 pop_menu_show(w, w->childlist->childs[0], 6, true);
                 break;
             }
         }
     }
     transparent_draw(w_, user_data);
 }
References Widget_t::app, Widget_t::childlist, childlist_has_child(), Childlist_t::childs, Xputty::dpy, Childlist_t::elem, Xputty::hold_grab, Widget_t::parent, pop_menu_show(), transparent_draw(), and widget_hide().
_configure_menu()
void _configure_menu (Widget_t * parent, Widget_t * menu, int elem, bool above)
_configure_menu - set final size and position of menu to a Widget_t
Parameters
*parent - pointer to the Widget_t the menu should pop over
*menu - the menu to show
Returns
void
Definition at line 281 of file xmenu_private.c.
{
     Widget_t* view_port =  menu->childlist->childs[0];
     if (!view_port->childlist->elem) return;
     XWindowAttributes attrs;
     XGetWindowAttributes(menu->app->dpy, (Window)view_port->childlist->childs[0]->widget, &attrs);
     int height = attrs.height;
     int x1, y1;
     int posy = (above) ? parent->height : 0;
     Window child;
     XTranslateCoordinates( parent->app->dpy, parent->widget, DefaultRootWindow(parent->app->dpy), 0, posy, &x1, &y1, &child );
     int item_width = 1.0;
     cairo_text_extents_t extents;
     int i = view_port->childlist->elem-1;
     set_adjustment(view_port->adj,0.0, view_port->adj->value, 0.0, i-(elem-1),1.0, CL_VIEWPORT);
     bool is_not_scrolable = false;
     if(view_port->childlist->elem <= elem) {
         elem = view_port->childlist->elem;
         is_not_scrolable = true;
     }
     for(;i>-1;i--) {
         Widget_t *w = view_port->childlist->childs[i];
         cairo_set_font_size (w->crb, height/2);
         cairo_text_extents(w->crb,w->label , &extents);
         item_width = max(item_width, (int)extents.width+40);
         if(is_not_scrolable) w->scale.gravity = NORTHEAST;
     }
     if(above) {
         if(item_width<parent->width)item_width = parent->width;
     }
     XResizeWindow (menu->app->dpy, menu->widget, item_width, height*elem);
     XResizeWindow (view_port->app->dpy, view_port->widget, item_width, height*view_port->childlist->elem);
     XMoveWindow(menu->app->dpy,menu->widget,x1, y1);
 }
References Widget_t::adj, Widget_t::app, Widget_t::childlist, Childlist_t::childs, CL_VIEWPORT, Widget_t::crb, Xputty::dpy, Childlist_t::elem, Resize_t::gravity, Widget_t::height, Widget_t::label, max, NORTHEAST, Widget_t::scale, set_adjustment(), Adjustment_t::value, Widget_t::widget, and Widget_t::width.
_draw_accel_item()
void _draw_accel_item (void * w_, void * user_data)
_draw_accel_item - draw accel item on expose call
Parameters
*w_ - the item to draw
*user_data - attached user_data
Returns
void
show label
Definition at line 162 of file xmenu_private.c.
{
     Widget_t *w = (Widget_t*)w_;
     if (!w) return;
     XWindowAttributes attrs;
     XGetWindowAttributes(w->app->dpy, (Window)w->widget, &attrs);
     int width = attrs.width;
     int height = attrs.height;
     if (attrs.map_state != IsViewable) return;
     use_base_color_scheme(w, NORMAL_);
     cairo_rectangle(w->crb, 0, 0, width , height);
     if(w->state==1) {
         use_base_color_scheme(w, PRELIGHT_);
     } else if(w->state==2) {
         use_base_color_scheme(w, SELECTED_);
     } else if(w->state==3) {
         use_base_color_scheme(w, ACTIVE_);
     }
     cairo_fill_preserve(w->crb);
     cairo_set_line_width(w->crb, 1.0);
     use_frame_color_scheme(w, PRELIGHT_);
     cairo_stroke(w->crb);
     cairo_text_extents_t extents;
     /** show label **/
     use_text_color_scheme(w, get_color_state(w));
     cairo_set_font_size (w->crb, height/2);
     if (strstr(w->label, "_")) {
         cairo_text_extents(w->crb, "--", &extents);
         double underline = extents.width;
         strcpy(w->input_label,w->label);
         int pos = _menu_remove_low_dash(w->input_label);
         cairo_text_extents(w->crb,w->input_label , &extents);
         cairo_move_to (w->crb, (width-extents.width)*0.5, (height+extents.height)*0.5);
         cairo_show_text(w->crb, w->input_label);
         cairo_set_line_width(w->crb, 1.0);
         cairo_move_to (w->crb, (width-extents.width)*0.5 + (pos * underline), (height+extents.height)*0.55);
         cairo_line_to(w->crb,(width-extents.width)*0.5 + ((pos+1) * underline), (height+extents.height)*0.55);
         cairo_stroke(w->crb);
     } else {
         cairo_text_extents(w->crb,w->label , &extents);
         cairo_move_to (w->crb, (width-extents.width)*0.5, (height+extents.height)*0.5);
         cairo_show_text(w->crb, w->label);
     }
     cairo_new_path (w->crb);
 }
References _menu_remove_low_dash(), ACTIVE_, Widget_t::app, Widget_t::crb, Xputty::dpy, get_color_state(), Widget_t::input_label, Widget_t::label, NORMAL_, PRELIGHT_, SELECTED_, Widget_t::state, use_base_color_scheme(), use_frame_color_scheme(), use_text_color_scheme(), and Widget_t::widget.
_draw_check_item()
void _draw_check_item (void * w_, void * user_data)
_draw_check_item - draw item on expose call
Parameters
*w_ - the item to draw
*user_data - attached user_data
Returns
void
Definition at line 210 of file xmenu_private.c.
{
     _draw_item(w_, user_data);
     Widget_t *w = (Widget_t*)w_;
     XWindowAttributes attrs;
     XGetWindowAttributes(w->app->dpy, (Window)w->widget, &attrs);
     int height = attrs.height;
     if (w->flags & IS_RADIO) {
         cairo_arc(w->crb, height/3, height/2, height/6, 0, 2 * M_PI );
     } else {
         cairo_rectangle(w->crb, height/6, height/3, height/3 , height/3);
     }
     use_shadow_color_scheme(w, get_color_state(w));
     cairo_fill(w->crb);
     if ((int) w->adj_y->value) {
         if (w->flags & IS_RADIO) {
             cairo_arc(w->crb, height/3, height/2, height/6-2, 0, 2 * M_PI );
         } else {
             cairo_rectangle(w->crb, height/6+1, height/3+1, height/3-2 , height/3-2);
         }
         use_fg_color_scheme(w, ACTIVE_);
         cairo_fill(w->crb);
     }
 }
References _draw_item(), ACTIVE_, Widget_t::adj_y, Widget_t::app, Widget_t::crb, Xputty::dpy, Widget_t::flags, get_color_state(), IS_RADIO, use_fg_color_scheme(), use_shadow_color_scheme(), Adjustment_t::value, and Widget_t::widget.
_draw_item()
void _draw_item (void * w_, void * user_data)
_draw_item - draw item on expose call
Parameters
*w_ - the item to draw
*user_data - attached user_data
Returns
void
show label
Definition at line 129 of file xmenu_private.c.
{
     Widget_t *w = (Widget_t*)w_;
     if (!w) return;
     XWindowAttributes attrs;
     XGetWindowAttributes(w->app->dpy, (Window)w->widget, &attrs);
     int width = attrs.width;
     int height = attrs.height;
     if (attrs.map_state != IsViewable) return;
     use_base_color_scheme(w, NORMAL_);
     cairo_rectangle(w->crb, 0, 0, width , height);
     if(w->state==1) {
         use_base_color_scheme(w, PRELIGHT_);
     } else if(w->state==2) {
         use_base_color_scheme(w, SELECTED_);
     } else if(w->state==3) {
         use_base_color_scheme(w, ACTIVE_);
     }
     cairo_fill_preserve(w->crb);
     cairo_set_line_width(w->crb, 1.0);
     use_frame_color_scheme(w, PRELIGHT_);
     cairo_stroke(w->crb);
     cairo_text_extents_t extents;
     /** show label **/
     use_text_color_scheme(w, get_color_state(w));
     cairo_set_font_size (w->crb, height/2);
     cairo_text_extents(w->crb,w->label , &extents);
     cairo_move_to (w->crb, (width-extents.width)*0.5, (height+extents.height)*0.5);
     cairo_show_text(w->crb, w->label);
     cairo_new_path (w->crb);
 }
References ACTIVE_, Widget_t::app, Widget_t::crb, Xputty::dpy, get_color_state(), Widget_t::label, NORMAL_, PRELIGHT_, SELECTED_, Widget_t::state, use_base_color_scheme(), use_frame_color_scheme(), use_text_color_scheme(), and Widget_t::widget.
_draw_menu()
void _draw_menu (void * w_, void * user_data)
_draw_menu - draw menu on expose call
Parameters
*w_ - the menu to draw
*user_data - attached user_data
Returns
void
Definition at line 122 of file xmenu_private.c.
{
     Widget_t *w = (Widget_t*)w_;
     if (!w) return;
     use_bg_color_scheme(w, get_color_state(w));
     cairo_paint (w->crb);
 }
References Widget_t::crb, get_color_state(), and use_bg_color_scheme().
_draw_menu_label()
void _draw_menu_label (void * w_, void * user_data)
_draw_menu_label - draw the menu label on expose call
Parameters
*w_ - the menu to draw
*user_data - attached user_data
Returns
void
Definition at line 44 of file xmenu_private.c.
{
     Widget_t *w = (Widget_t*)w_;
     XWindowAttributes attrs;
     XGetWindowAttributes(w->app->dpy, (Window)w->widget, &attrs);
     int width = attrs.width;
     int height = attrs.height;
     cairo_text_extents_t extents;
     use_text_color_scheme(w, get_color_state(w));
     cairo_set_font_size (w->crb, w->app->normal_font/w->scale.ascale);
     cairo_text_extents(w->crb, "A", &extents);
     double lh = extents.height;
     if (strstr(w->label, "_")) {
         cairo_text_extents(w->crb, "--", &extents);
         double underline = extents.width;
         strcpy(w->input_label,w->label);
         int pos = _menu_remove_low_dash(w->input_label);
         cairo_text_extents(w->crb,w->input_label , &extents);
         cairo_move_to (w->crb, (width-extents.width)*0.5, (height+lh)*0.5);
         cairo_show_text(w->crb, w->input_label);
         cairo_set_line_width(w->crb, 1.0);
         cairo_move_to (w->crb, (width-extents.width)*0.5 + (pos * underline), (height+lh)*0.55);
         cairo_line_to(w->crb,(width-extents.width)*0.5 + ((pos+1) * underline), (height+lh)*0.55);
         cairo_stroke(w->crb);
     } else {
         cairo_text_extents(w->crb,w->label , &extents);
         cairo_move_to (w->crb, (width-extents.width)*0.5, (height+lh)*0.5);
         cairo_show_text(w->crb, w->label);
     }
     cairo_new_path (w->crb);
 }
References _menu_remove_low_dash(), Widget_t::app, Resize_t::ascale, Widget_t::crb, Xputty::dpy, get_color_state(), Widget_t::input_label, Widget_t::label, Xputty::normal_font, Widget_t::scale, use_text_color_scheme(), and Widget_t::widget.
_draw_viewslider()
void _draw_viewslider (void * w_, void * user_data)
_draw_viewslider - draw a slider on the viewport to indicate the view point
Parameters
*w_ - void pointer to view_port
*user_data - attached user_data
Returns
void
Definition at line 234 of file xmenu_private.c.
{
     Widget_t *w = (Widget_t*)w_;
     int v = (int)w->adj->max_value;
     if (!v) return;
     XWindowAttributes attrs;
     XGetWindowAttributes(w->app->dpy, (Window)w->widget, &attrs);
     if (attrs.map_state != IsViewable) return;
     int width = attrs.width;
     int height = attrs.height;
     float sliderstate = adj_get_state(w->adj);
     use_bg_color_scheme(w, NORMAL_);
     cairo_rectangle(w->crb, width-5,0,5,height);
     cairo_fill_preserve(w->crb);
     use_shadow_color_scheme(w, NORMAL_);
     cairo_fill(w->crb);
     use_bg_color_scheme(w, NORMAL_);
     cairo_rectangle(w->crb, width-5,(height-10)*sliderstate,5,10);
     cairo_fill_preserve(w->crb);
     use_fg_color_scheme(w, NORMAL_);
     cairo_set_line_width(w->crb,1);
     cairo_stroke(w->crb);
 }
References Widget_t::adj, adj_get_state(), Widget_t::app, Widget_t::crb, Xputty::dpy, Adjustment_t::max_value, NORMAL_, use_bg_color_scheme(), use_fg_color_scheme(), use_shadow_color_scheme(), and Widget_t::widget.
_menu_entry_released()
void _menu_entry_released (void * w_, void * item_, void * user_data)
_menu_entry_released - the menu release func
Parameters
*w_ - void pointer to the Widget_t menu
<em>item - void pointer to the selected item *(int)
*user_data - void pointer to the item label *(const char**)
Returns
void
Definition at line 105 of file xmenu_private.c.
{
     Widget_t *w = (Widget_t*)w_;
     Widget_t * bar = NULL;
     int i = w->app->childlist->elem-1;
     for(;i>-1;i--) {
         Widget_t *wid = w->app->childlist->childs[i];
         if (wid == w) {
             bar = w->app->childlist->childs[i-1];
             int old_value = (int)adj_get_value(bar->adj);
             adj_set_value(bar->adj, (float)*(int*)item_);
             if (old_value == *(int*)item_)
                 bar->func.value_changed_callback(bar, NULL);
             break;
         }
     }
 }
References Widget_t::adj, adj_get_value(), adj_set_value(), Widget_t::app, Xputty::childlist, Childlist_t::childs, Childlist_t::elem, Widget_t::func, and Func_t::value_changed_callback.
_menu_released()
void _menu_released (void * w_, void * button_, void * user_data)
_menu_released - popup the menu on click
Parameters
*w_ - void pointer to the Widget_t button
*button - void pointer to XEvent.xbutton struct
*user_data - void pointer to attached user_data
Returns
void
Definition at line 97 of file xmenu_private.c.
{
     Widget_t *w = (Widget_t*)w_;
     XButtonEvent *xbutton = (XButtonEvent*)button_;
     if (w->flags & HAS_POINTER && xbutton->button == Button1) {
         pop_menu_show(w, w->childlist->childs[0], 6, true);
     }
 }
References Widget_t::childlist, Childlist_t::childs, Widget_t::flags, HAS_POINTER, and pop_menu_show().
_menu_remove_low_dash()
int _menu_remove_low_dash (char * str)
Definition at line 25 of file xmenu_private.c.
{
     char *src;
     char *dst;
     int i = 0;
     int r = 0;
     for (src = dst = str; *src != '\0'; src++) {
         *dst = *src;
         if (*dst != '_') {
             dst++;
         } else {
             r = i;
         }
         i++;
     }
     *dst = '\0';
     return r;
 }
_radio_item_button_pressed()
void _radio_item_button_pressed (void * w_, void * button_, void * user_data)
_radio_item_button_pressed - redraw item on button press
Parameters
*button - the xbutton which is pressed
*user_data - attached user_data
Returns
void
Definition at line 274 of file xmenu_private.c.
{
     Widget_t *w = (Widget_t*)w_;
     if (w->flags & HAS_FOCUS) {
         radio_item_set_active(w);
     }
 }
References Widget_t::flags, HAS_FOCUS, and radio_item_set_active().
_set_viewpoint()
void _set_viewpoint (void * w_, void * user_data)
_set_viewpoint - move the view_port to position
Parameters
*w_ - void pointer to view_port
*user_data - attached user_data
Returns
void
Definition at line 257 of file xmenu_private.c.
{
     Widget_t *w = (Widget_t*)w_;
     int v = (int)max(0,adj_get_value(w->adj));
     XWindowAttributes attrs;
     XGetWindowAttributes(w->app->dpy, (Window)w->childlist->childs[0]->widget, &attrs);
     int height = attrs.height;
     XMoveWindow(w->app->dpy,w->widget,0, -height*v);
 }
References Widget_t::adj, adj_get_value(), Widget_t::app, Widget_t::childlist, Childlist_t::childs, Xputty::dpy, max, and Widget_t::widget.