libxputty: xmeter.h File Reference
xmeter.h File Reference
#include "xputty.h"
Macros
#define XMETER_H_
Functions
float power2db (Widget_t *w, float power)
power2db - power (db) input to db output consider falloff
Widget_t * add_vmeter (Widget_t *parent, const char *label, bool show_scale, int x, int y, int width, int height)
add_vmeter - add a vumeter to a Widget_t connect to func.value_changed_callback to implement your actions
Widget_t * add_hmeter (Widget_t *parent, const char *label, bool show_scale, int x, int y, int width, int height)
add_hmeter - add a vumeter to a Widget_t connect to func.value_changed_callback to implement your actions
Macro Definition Documentation
XMETER_H_
#define XMETER_H_
Definition at line 25 of file xmeter.h.
Function Documentation
add_hmeter()
Widget_t* add_hmeter (Widget_t * parent, const char * label, bool show_scale, int x, int y, int width, int height)
add_hmeter - add a vumeter to a Widget_t connect to func.value_changed_callback to implement your actions
Parameters
*parent - pointer to the Widget_t request the vumeter
*label - Label to show on the vumeter
x,y,width,height - the position/geometry to create the vumeter
Returns
Widget_t* - pointer to the Widget_t meter struct
Definition at line 65 of file xmeter.c.
References _create_horizontal_meter_image(), _draw_h_meter(), _draw_hmeter_scale(), add_adjustment(), Widget_t::adj, Widget_t::adj_x, Widget_t::app, ASPECT, CL_METER, create_widget(), Func_t::expose_callback, Widget_t::func, Resize_t::gravity, Widget_t::label, and Widget_t::scale.
{
     Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
     _create_horizontal_meter_image(wid, width, height);
     wid->label = label;
     wid->adj_x = add_adjustment(wid,-70.0, -70.0, -70.0, 6.0,0.001, CL_METER);
     wid->adj = wid->adj_x;
     wid->scale.gravity = ASPECT;
     wid->func.expose_callback = _draw_h_meter;
     if (show_scale) {
         Widget_t *wid2 = create_widget(parent->app, parent, x, y+height, width, height);
         wid2->scale.gravity = ASPECT;
         wid2->func.expose_callback =_draw_hmeter_scale;
     }
     return wid;
 }
add_vmeter()
Widget_t* add_vmeter (Widget_t * parent, const char * label, bool show_scale, int x, int y, int width, int height)
add_vmeter - add a vumeter to a Widget_t connect to func.value_changed_callback to implement your actions
Parameters
*parent - pointer to the Widget_t request the vumeter
*label - Label to show on the vumeter
x,y,width,height - the position/geometry to create the vumeter
Returns
Widget_t* - pointer to the Widget_t mete struct
Definition at line 47 of file xmeter.c.
References _create_vertical_meter_image(), _draw_v_meter(), _draw_vmeter_scale(), add_adjustment(), Widget_t::adj, Widget_t::adj_y, Widget_t::app, ASPECT, CL_METER, create_widget(), Func_t::expose_callback, Widget_t::func, Resize_t::gravity, Widget_t::label, and Widget_t::scale.
{
     Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
     _create_vertical_meter_image(wid, width, height);
     wid->label = label;
     wid->adj_y = add_adjustment(wid,-70.0, -70.0, -70.0, 6.0,0.001, CL_METER);
     wid->adj = wid->adj_y;
     wid->scale.gravity = ASPECT;
     wid->func.expose_callback = _draw_v_meter;
     if (show_scale) {
         Widget_t *wid2 = create_widget(parent->app, parent, x+width, y, width, height);
         wid2->scale.gravity = ASPECT;
         wid2->func.expose_callback =_draw_vmeter_scale;
     }
     return wid;
 }
power2db()
float power2db (Widget_t * w, float power)
power2db - power (db) input to db output consider falloff
Parameters
power - mesured power
Returns
float - calculated db
Definition at line 26 of file xmeter.c.
References Widget_t::adj, max, min, Adjustment_t::start_value, and Adjustment_t::std_value.
{
     const float falloff = 27 * 60 * 0.0005;
     const float fallsoft = 6 * 60 * 0.0005;
     //power = 20.*log10(power);
     if (power <=  20.*log10(0.00021)) { // -70db
         power = 20.*log10(0.00000000001); //-137db
         w->adj->start_value = min(0.0,w->adj->start_value - fallsoft);
     }
     // retrieve old meter value and consider falloff
     if (power < w->adj->std_value) {
         power = max(power, w->adj->std_value - falloff);
         w->adj->start_value = min(0.0,w->adj->start_value - fallsoft);
     }
     if (power > w->adj->start_value) {
         w->adj->start_value = power ;
     }
     w->adj->std_value = power;
     return  power;
 }