libxputty: xplayhead.c File Reference
xplayhead.c File Reference
#include "xplayhead.h"
#include "xplayhead_private.h"
Functions
void playhead_mem_free (void *w_, void *user_data)
Widget_t * add_playhead (Widget_t *parent, const char *label, Adjustment_t *clip, Adjustment_t *cut, int x, int y, int width, int height)
add_playhead - add a playhead to a Widget_t connect to func.value_changed_callback to implement your actions
Function Documentation
add_playhead()
Widget_t* add_playhead (Widget_t * parent, const char * label, Adjustment_t * clip, Adjustment_t * cut, int x, int y, int width, int height)
add_playhead - add a playhead to a Widget_t connect to func.value_changed_callback to implement your actions
Parameters
*parent - pointer to the Widget_t request the vumeter
*label - Label to show on the vumeter
x,y,width,height - the position/geometry to create the vumeter
Returns
Widget_t* - pointer to the Widget_t meter struct
Definition at line 32 of file xplayhead.c.
{
     Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
     _create_playhead_image(wid, width, height);
     wid->flags |= HAS_MEM;
     wid->label = label;
     wid->adj = add_adjustment(wid,0.0, 0.0, 0.0, 1000.0,1.0, CL_METER);
     wid->adj_x = clip;
     wid->adj_y = cut;
     wid->scale.gravity = ASPECT;
     wid->func.expose_callback = _draw_playhead;
     wid->func.mem_free_callback = playhead_mem_free;
     return wid;
 }
References _create_playhead_image(), _draw_playhead(), add_adjustment(), Widget_t::adj, Widget_t::adj_x, Widget_t::adj_y, Widget_t::app, ASPECT, CL_METER, create_widget(), Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, HAS_MEM, Widget_t::label, Func_t::mem_free_callback, playhead_mem_free(), and Widget_t::scale.
playhead_mem_free()
void playhead_mem_free (void * w_, void * user_data)
Definition at line 25 of file xplayhead.c.
{
     Widget_t *wid = (Widget_t*)w_;
     wid->adj_x = NULL;
     wid->adj_y = NULL;
 }
References Widget_t::adj_x, and Widget_t::adj_y.