libxputty: xplayhead_private.c File Reference
xplayhead_private.c File Reference
#include "xplayhead_private.h"
Functions
void _create_playhead_image (Widget_t *w, int width, int height)
_create_playhead_image - internal draw the playhead image to the cairo image surface
void _draw_playhead (void *w_, void *user_data)
_draw_playhead - internal draw the playhead to the buffer
Function Documentation
_create_playhead_image()
void _create_playhead_image (Widget_t * w, int width, int height)
_create_playhead_image - internal draw the playhead image to the cairo image surface
Parameters
*w - pointer to the Widget_t meter
width - widget width
height - widget height
Returns
void
Definition at line 25 of file xplayhead_private.c.
{
     w->image = cairo_surface_create_similar (w->surface,
                         CAIRO_CONTENT_COLOR_ALPHA, width, height*2);
     cairo_t *cri = cairo_create (w->image);
     Colors *c = get_color_scheme(w->app, NORMAL_);
     //cairo_rectangle(cri,0.0, 0.0, width, height*2);
     //cairo_set_source_rgba (cri, c->bg[0],  c->bg[1], c->bg[2],  c->bg[3]);
     //cairo_fill(cri);
     cairo_set_source_rgba (cri, c->shadow[0],  c->shadow[1], c->shadow[2],  c->shadow[3]);
     int h = height ;
     int ci = h-2;
     int i = 1;
     for(;i<width;) {
         cairo_rectangle(cri,i,1,2,ci);
         cairo_fill(cri);
         i +=3;
     }
     cairo_set_source_rgba (cri, c->text[0],  c->text[1], c->text[2],  c->text[3]);
     i = 1;
     for(;i<width;) {
         cairo_rectangle(cri,i,height+1,2,ci);
         cairo_fill(cri);
         i +=3;
     }
     cairo_destroy(cri);
 }
References Widget_t::app, get_color_scheme(), Widget_t::image, NORMAL_, Colors::shadow, Widget_t::surface, and Colors::text.
_draw_playhead()
void _draw_playhead (void * w_, void * user_data)
_draw_playhead - internal draw the playhead to the buffer
Parameters
*w_ - void pointer to the Widget_t button
*user_data - void pointer to attached user_data
Returns
void
Definition at line 59 of file xplayhead_private.c.
{
     Widget_t *w = (Widget_t*)w_;
     int width = cairo_xlib_surface_get_width(w->image);
     int height = cairo_xlib_surface_get_height(w->image);
     double state = adj_get_state(w->adj);
     double clip = adj_get_state(w->adj_x);
     double cut = adj_get_state(w->adj_y);
     widget_set_scale(w);
     cairo_set_source_surface (w->crb, w->image, 0, 0);
     cairo_rectangle(w->crb,0, 0, width, height/2);
     cairo_fill(w->crb);
     cairo_set_source_surface (w->crb, w->image, 0, -height/2);
     cairo_rectangle(w->crb, width*state,0,3, height/2);
     cairo_fill(w->crb);
     cairo_set_source_rgba (w->crb, 0.5, 0.0, 0.0, 0.4);
     cairo_rectangle(w->crb, 0,0,width*clip, height/2);
     cairo_fill(w->crb);
     cairo_rectangle(w->crb, width,0,(width*cut)-width, height/2);
     cairo_fill(w->crb);
     widget_reset_scale(w);
 }
References Widget_t::adj, adj_get_state(), Widget_t::adj_x, Widget_t::adj_y, Widget_t::crb, Widget_t::image, widget_reset_scale(), and widget_set_scale().