libxputty: xpngloader.c File Reference
xpngloader.c File Reference
#include "xpngloader.h"
Functions
cairo_status_t png_stream_reader (void *_stream, unsigned char *data, unsigned int length)
cairo_surface_t * cairo_image_surface_create_from_stream (const unsigned char *name)
cairo_image_surface_create_from_stream - read binary data into cairo surface from stream
void widget_get_png (Widget_t *w, const unsigned char *name)
widget_get_png - read png into Widget_t xlib surface
void widget_get_scaled_png (Widget_t *w, const unsigned char *name)
widget_get_scaled_png - read scaled png into Widget_t xlib surface
void widget_get_surface_ptr (Widget_t *w, Widget_t *wid)
widget_get_surface_ptr - set pointer to a 2. Widget_t xlib surface
cairo_surface_t * surface_get_png (Widget_t *w, cairo_surface_t *sf, const unsigned char *name)
surface_get_png - read png into Widget_t xlib surface
void widget_set_icon_from_surface (Widget_t *w, Pixmap *icon_, cairo_surface_t *image)
widget_set_icon_from_surface - set icon image from cairo surface for Widget_t those icon will be used in the Window decoration and the toolbar (depending on the Widnow manager)
void widget_set_icon_from_png (Widget_t *w, Pixmap *icon_, const unsigned char *name)
widget_set_icon_from_png - set icon image from png binary to Widget_t those icon will be used in the Window decoration and the toolbar (depending on the Widnow manager)
Function Documentation
cairo_image_surface_create_from_stream()
cairo_surface_t* cairo_image_surface_create_from_stream (const unsigned char * name)
cairo_image_surface_create_from_stream - read binary data into cairo surface from stream
Parameters
*name - pointer to the binary image data LDVAR(name)
Returns
cairo_surface_t - the cairo_image_surface
Definition at line 34 of file xpngloader.c.
{
     binary_stream png_stream;
     png_stream.data = name;
     png_stream.position = 0;
     return cairo_image_surface_create_from_png_stream(&png_stream_reader, (void *)&png_stream);
 }
References binary_stream::data, png_stream_reader(), and binary_stream::position.
png_stream_reader()
cairo_status_t png_stream_reader (void * _stream, unsigned char * data, unsigned int length)
Definition at line 27 of file xpngloader.c.
{
     binary_stream * stream = (binary_stream *) _stream;
     memcpy(data, &stream->data[stream->position],length);
     stream->position += length;
     return CAIRO_STATUS_SUCCESS;
 }
References binary_stream::data, and binary_stream::position.
surface_get_png()
cairo_surface_t* surface_get_png (Widget_t * w, cairo_surface_t * sf, const unsigned char * name)
surface_get_png - read png into Widget_t xlib surface
Parameters
*w - pointer to the Widget_t which should use the png
*sf - pointer to the cairo_surface_t which should hold the png
*name - pointer to the binary image data LDVAR(name)
Returns
cairo_surface_t - the cairo_xlib_surface, you need to free it by yourself
Definition at line 83 of file xpngloader.c.
{
     cairo_surface_t *getpng = cairo_image_surface_create_from_stream (name);
     int width = cairo_image_surface_get_width(getpng);
     int height = cairo_image_surface_get_height(getpng);
     sf = cairo_surface_create_similar (w->surface,
                         CAIRO_CONTENT_COLOR_ALPHA, width, height);
     cairo_t *cri = cairo_create (sf);
     cairo_set_source_surface (cri, getpng,0,0);
     cairo_paint (cri);
     cairo_surface_destroy(getpng);
     cairo_destroy(cri);
     return sf;
 }
References cairo_image_surface_create_from_stream(), and Widget_t::surface.
widget_get_png()
void widget_get_png (Widget_t * w, const unsigned char * name)
widget_get_png - read png into Widget_t xlib surface
Parameters
*w - pointer to the Widget_t which should use the png
*name - pointer to the binary image data LDVAR(name)
Returns
void
Definition at line 41 of file xpngloader.c.
{
     cairo_surface_t *getpng = cairo_image_surface_create_from_stream (name);
     int width = cairo_image_surface_get_width(getpng);
     int height = cairo_image_surface_get_height(getpng);
     cairo_surface_destroy(w->image);
     w->image = NULL;
     w->image = cairo_surface_create_similar (w->surface,
                         CAIRO_CONTENT_COLOR_ALPHA, width, height);
     cairo_t *cri = cairo_create (w->image);
     cairo_set_source_surface (cri, getpng,0,0);
     cairo_paint (cri);
     cairo_surface_destroy(getpng);
     cairo_destroy(cri);
 }
References cairo_image_surface_create_from_stream(), Widget_t::image, and Widget_t::surface.
widget_get_scaled_png()
void widget_get_scaled_png (Widget_t * w, const unsigned char * name)
widget_get_scaled_png - read scaled png into Widget_t xlib surface
Parameters
*w - pointer to the Widget_t which should use the png
*name - pointer to the binary image data LDVAR(name)
Returns
void
Definition at line 57 of file xpngloader.c.
{
     cairo_surface_t *getpng = cairo_image_surface_create_from_stream (name);
     int width = cairo_image_surface_get_width(getpng);
     int height = cairo_image_surface_get_height(getpng);
     int width_t = w->scale.init_width;
     int height_t = w->scale.init_height;
     double x = (double)width_t/(double)width;
     double y = (double)height_t/(double)height;
     cairo_surface_destroy(w->image);
     w->image = NULL;
     w->image = cairo_surface_create_similar (w->surface,
                         CAIRO_CONTENT_COLOR_ALPHA, width_t, height_t);
     cairo_t *cri = cairo_create (w->image);
     cairo_scale(cri, x,y);
     cairo_set_source_surface (cri, getpng,0,0);
     cairo_paint (cri);
     cairo_surface_destroy(getpng);
     cairo_destroy(cri);
 }
References cairo_image_surface_create_from_stream(), Widget_t::image, Resize_t::init_height, Resize_t::init_width, Widget_t::scale, and Widget_t::surface.
widget_get_surface_ptr()
void widget_get_surface_ptr (Widget_t * w, Widget_t * wid)
widget_get_surface_ptr - set pointer to a 2. Widget_t xlib surface
Parameters
*w - pointer to the Widget_t which should use the surface
*wid - pointer to the Widget_t which hold the surface
Returns
void
Definition at line 78 of file xpngloader.c.
{
     w->image = wid->image;
     w->flags |= REUSE_IMAGE;
 }
References Widget_t::flags, Widget_t::image, and REUSE_IMAGE.
widget_set_icon_from_png()
void widget_set_icon_from_png (Widget_t * w, Pixmap * icon_, const unsigned char * name)
widget_set_icon_from_png - set icon image from png binary to Widget_t those icon will be used in the Window decoration and the toolbar (depending on the Widnow manager)
Parameters
*w - pointer to the Widget_t which should use the icon
*name - pointer to the binary image data LDVAR(name)
Returns
void
Definition at line 124 of file xpngloader.c.
{
     cairo_surface_t *image = cairo_image_surface_create_from_stream (name);
     int width = cairo_image_surface_get_width(image);
     int height = cairo_image_surface_get_height(image);
     XWindowAttributes atr;
     XGetWindowAttributes (w->app->dpy, w->widget, &atr);
     Pixmap icon = XCreatePixmap(w->app->dpy, w->widget, width, height, atr.depth);
     cairo_surface_t *surface = cairo_xlib_surface_create (w->app->dpy, icon,
                   DefaultVisual(w->app->dpy, DefaultScreen(w->app->dpy)), width, height);
     cairo_t *cri = cairo_create (surface);
     Colors *c = get_color_scheme(w->app, PRELIGHT_);
     cairo_set_source_rgba(cri, c->bg[0],  c->bg[1], c->bg[2],  c->bg[3]);
     cairo_paint(cri);
     cairo_set_source_surface (cri, image,0,0);
     cairo_paint(cri);
     cairo_surface_destroy(image);
     cairo_surface_destroy(surface);
     cairo_destroy(cri);
     icon_ = &icon;
     XWMHints* win_hints = XAllocWMHints();
     assert(win_hints);
     win_hints->flags = IconPixmapHint;
     win_hints->icon_pixmap = icon;
     XSetWMHints(w->app->dpy, w->widget, win_hints);
     XFree(win_hints);
 }
References Widget_t::app, Colors::bg, cairo_image_surface_create_from_stream(), Xputty::dpy, get_color_scheme(), PRELIGHT_, and Widget_t::widget.
widget_set_icon_from_surface()
void widget_set_icon_from_surface (Widget_t * w, Pixmap * icon_, cairo_surface_t * image)
widget_set_icon_from_surface - set icon image from cairo surface for Widget_t those icon will be used in the Window decoration and the toolbar (depending on the Widnow manager)
Parameters
*w - pointer to the Widget_t which should use the icon
*image - pointer to the cairo_surface_t to use for the icon
Returns
void
Definition at line 98 of file xpngloader.c.
{
     int width = cairo_xlib_surface_get_width(image);
     int height = cairo_xlib_surface_get_height(image);
     XWindowAttributes atr;
     XGetWindowAttributes (w->app->dpy, w->widget, &atr);
     Pixmap icon = XCreatePixmap(w->app->dpy, w->widget, width, height, atr.depth);
     cairo_surface_t *surface = cairo_xlib_surface_create (w->app->dpy, icon,
                   DefaultVisual(w->app->dpy, DefaultScreen(w->app->dpy)), width, height);
     cairo_t *cri = cairo_create (surface);
     Colors *c = get_color_scheme(w->app, PRELIGHT_);
     cairo_set_source_rgba(cri, c->bg[0],  c->bg[1], c->bg[2],  c->bg[3]);
     cairo_paint(cri);
     cairo_set_source_surface (cri, image,0,0);
     cairo_paint(cri);
     cairo_surface_destroy(surface);
     cairo_destroy(cri);
     icon_ = &icon;
     XWMHints* win_hints = XAllocWMHints();
     assert(win_hints);
     win_hints->flags = IconPixmapHint;
     win_hints->icon_pixmap = icon;
     XSetWMHints(w->app->dpy, w->widget, win_hints);
     XFree(win_hints);
 }
References Widget_t::app, Colors::bg, Xputty::dpy, get_color_scheme(), PRELIGHT_, and Widget_t::widget.