libxputty: xpngloader.h File Reference
xpngloader.h File Reference
#include "xputty.h"
#include "xresources.h"
Data Structures
struct binary_stream
binary_stream - struct definition to read binary data into cairo surface
Macros
#define XPNGLOADER_H_
#define EXTLD(NAME)
#define LDVAR(NAME) _binary_ ## NAME ## _start
#define LDLEN(NAME) ((_binary_ ## NAME ## _end) - (_binary_ ## NAME ## _start))
Functions
cairo_surface_t * cairo_image_surface_create_from_stream (const unsigned char *name)
cairo_image_surface_create_from_stream - read binary data into cairo surface from stream
void widget_get_png (Widget_t *w, const unsigned char *name)
widget_get_png - read png into Widget_t xlib surface
void widget_set_icon_from_surface (Widget_t *w, Pixmap *icon_, cairo_surface_t *image)
widget_set_icon_from_surface - set icon image from cairo surface for Widget_t those icon will be used in the Window decoration and the toolbar (depending on the Widnow manager)
void widget_set_icon_from_png (Widget_t *w, Pixmap *icon_, const unsigned char *name)
widget_set_icon_from_png - set icon image from png binary to Widget_t those icon will be used in the Window decoration and the toolbar (depending on the Widnow manager)
Macro Definition Documentation
EXTLD
#define EXTLD (NAME)
Value:
extern const unsigned char _binary_ ## NAME ## _start[]; \
  extern const unsigned char _binary_ ## NAME ## _end[];
define some MACROS to read png data from binary stream png's been converted to object files with ld -r -b binary name.png -o name.o
Definition at line 56 of file xpngloader.h.
LDLEN
#define LDLEN (NAME) ((_binary_ ## NAME ## _end) - (_binary_ ## NAME ## _start))
Definition at line 61 of file xpngloader.h.
LDVAR
#define LDVAR (NAME) _binary_ ## NAME ## _start
Definition at line 59 of file xpngloader.h.
XPNGLOADER_H_
#define XPNGLOADER_H_
Definition at line 25 of file xpngloader.h.
Function Documentation
cairo_image_surface_create_from_stream()
cairo_surface_t* cairo_image_surface_create_from_stream (const unsigned char * name)
cairo_image_surface_create_from_stream - read binary data into cairo surface from stream
Parameters
*name - pointer to the binary image data LDVAR(name)
Returns
cairo_surface_t - the cairo_image_surface
Definition at line 34 of file xpngloader.c.
References binary_stream::data, png_stream_reader(), and binary_stream::position.
{
     binary_stream png_stream;
     png_stream.data = name;
     png_stream.position = 0;
     return cairo_image_surface_create_from_png_stream(&png_stream_reader, (void *)&png_stream);
 }
widget_get_png()
void widget_get_png (Widget_t * w, const unsigned char * name)
widget_get_png - read png into Widget_t xlib surface
Parameters
*w - pointer to the Widget_t which should use the png
*name - pointer to the binary image data LDVAR(name)
Returns
void
Definition at line 41 of file xpngloader.c.
References cairo_image_surface_create_from_stream(), Widget_t::image, and Widget_t::surface.
{
     cairo_surface_t *getpng = cairo_image_surface_create_from_stream (name);
     int width = cairo_image_surface_get_width(getpng);
     int height = cairo_image_surface_get_height(getpng);
     w->image = cairo_surface_create_similar (w->surface,
                         CAIRO_CONTENT_COLOR_ALPHA, width, height);
     cairo_t *cri = cairo_create (w->image);
     cairo_set_source_surface (cri, getpng,0,0);
     cairo_paint (cri);
     cairo_surface_destroy(getpng);
     cairo_destroy(cri);
 }
widget_set_icon_from_png()
void widget_set_icon_from_png (Widget_t * w, Pixmap * icon_, const unsigned char * name)
widget_set_icon_from_png - set icon image from png binary to Widget_t those icon will be used in the Window decoration and the toolbar (depending on the Widnow manager)
Parameters
*w - pointer to the Widget_t which should use the icon
*name - pointer to the binary image data LDVAR(name)
Returns
void
Definition at line 81 of file xpngloader.c.
References Widget_t::app, Colors::bg, cairo_image_surface_create_from_stream(), Xputty::dpy, get_color_scheme(), PRELIGHT_, and Widget_t::widget.
{
     cairo_surface_t *image = cairo_image_surface_create_from_stream (name);
     int width = cairo_image_surface_get_width(image);
     int height = cairo_image_surface_get_height(image);
     XWindowAttributes atr;
     XGetWindowAttributes (w->app->dpy, w->widget, &atr);
     Pixmap icon = XCreatePixmap(w->app->dpy, w->widget, width, height, atr.depth);
     cairo_surface_t *surface = cairo_xlib_surface_create (w->app->dpy, icon,
                   DefaultVisual(w->app->dpy, DefaultScreen(w->app->dpy)), width, height);
     cairo_t *cri = cairo_create (surface);
     Colors *c = get_color_scheme(w->app, PRELIGHT_);
     cairo_set_source_rgba(cri, c->bg[0],  c->bg[1], c->bg[2],  c->bg[3]);
     cairo_paint(cri);
     cairo_set_source_surface (cri, image,0,0);
     cairo_paint(cri);
     cairo_surface_destroy(image);
     cairo_surface_destroy(surface);
     cairo_destroy(cri);
     icon_ = &icon;
     XWMHints* win_hints = XAllocWMHints();
     assert(win_hints);
     win_hints->flags = IconPixmapHint;
     win_hints->icon_pixmap = icon;
     XSetWMHints(w->app->dpy, w->widget, win_hints);
     XFree(win_hints);
 }
widget_set_icon_from_surface()
void widget_set_icon_from_surface (Widget_t * w, Pixmap * icon_, cairo_surface_t * image)
widget_set_icon_from_surface - set icon image from cairo surface for Widget_t those icon will be used in the Window decoration and the toolbar (depending on the Widnow manager)
Parameters
*w - pointer to the Widget_t which should use the icon
*image - pointer to the cairo_surface_t to use for the icon
Returns
void
Definition at line 55 of file xpngloader.c.
References Widget_t::app, Colors::bg, Xputty::dpy, get_color_scheme(), PRELIGHT_, and Widget_t::widget.
{
     int width = cairo_xlib_surface_get_width(image);
     int height = cairo_xlib_surface_get_height(image);
     XWindowAttributes atr;
     XGetWindowAttributes (w->app->dpy, w->widget, &atr);
     Pixmap icon = XCreatePixmap(w->app->dpy, w->widget, width, height, atr.depth);
     cairo_surface_t *surface = cairo_xlib_surface_create (w->app->dpy, icon,
                   DefaultVisual(w->app->dpy, DefaultScreen(w->app->dpy)), width, height);
     cairo_t *cri = cairo_create (surface);
     Colors *c = get_color_scheme(w->app, PRELIGHT_);
     cairo_set_source_rgba(cri, c->bg[0],  c->bg[1], c->bg[2],  c->bg[3]);
     cairo_paint(cri);
     cairo_set_source_surface (cri, image,0,0);
     cairo_paint(cri);
     cairo_surface_destroy(surface);
     cairo_destroy(cri);
     icon_ = &icon;
     XWMHints* win_hints = XAllocWMHints();
     assert(win_hints);
     win_hints->flags = IconPixmapHint;
     win_hints->icon_pixmap = icon;
     XSetWMHints(w->app->dpy, w->widget, win_hints);
     XFree(win_hints);
 }