libxputty: xputty.h File Reference
xputty.h File Reference
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stddef.h>
#include <assert.h>
#include <limits.h>
#include <math.h>
#include <cairo.h>
#include <cairo-xlib.h>
#include <X11/Xutil.h>
#include <X11/keysym.h>
#include <X11/Xatom.h>
#include "xwidget.h"
#include "xadjustment.h"
#include "xchildlist.h"
#include "xcolor.h"
#include "xpngloader.h"
Data Structures
struct Xputty
Xputty - the main struct.
It should be declared before any other call to a Xputty function.
Xputty store a pointer in the childlist, to any Widget_t related to this instance of libxputty.
The first created Widget_t is the toplevel window.
When the toplevel window call destroy_widget(), Xputty call destroy_widget() for all remaining Widget_t's in the main childlist.
So any allocated memory should be released before the toplevel window finaly close.
Macros
#define XPUTTY1_H_
#define DEBUG 0
#define NDEBUG
#define debug_print(...) ((void)((DEBUG) ? fprintf(stderr, __VA_ARGS__) : 0))
debug_print - print out state messages when compiled with the -DDEBUG flag
#define min(x, y) ((x) < (y) ? (x) : (y))
min - set a maximal value (x) as return value
#define max(x, y) ((x) < (y) ? (y) : (x))
max - set a minimal value (x) as return value
#define IS_UTF8(c) (((c)&0xc0)==0xc0)
IS_UTF8 - check if a char contain UTF 8 formated signs.
Typedefs
typedef struct Childlist_t Childlist_t
Childlist_t - maintain a Widget_t list of childs for a Widget_t.
typedef struct Adjustment_t Adjustment_t
Adjustment_t - Adjustment_t for a Widget_t.
typedef struct Widget_t Widget_t
Widget_t - the Widget_t base struct.
typedef struct XColor_t XColor_t
XColor_t - the Widget_t Color struct.
typedef struct Xputty Xputty
Xputty - the main struct.It should be declared before any other call to a Xputty function.
Functions
void main_init (Xputty *main)
main_init - open the Display and init the main->childlist.
Set the bool run to true.
The bool run is used to terminate the main event loop.
main_init() should be called directly after the declaration of Xputty before the first Widget_t get created.
Any Widget_t created afterwards will be added to the main childlist.
The main childlist is used to check if a Widget_t is valid to receive a Event.
Xputty check if a Widget_t is registerd in the main childlist, and only forward events when it found the Widget_t in the list.
When a Widget_t call destroy_widget() any childs of this Widget_t receive a call to destroy_widget() to release there memory, they get removed from the main childlist and finaly the Widget_t itself will be removed from the main childlist as well. On main_quit() any remaining Widget_t from the main childlist will be destroyed, to ensure that we leave the memory clean.
void main_run (Xputty *main)
main_run - start the main event loop.
It should be start after your Widget_t's been created.
You could create and destroy additional Widget_t's at any time later during run.
void run_embedded (Xputty *main)
run_embedded - the main event loop to run embedded UI's.
It should be start after your Widget_t's been created.
You could create and destroy additional Widget_t's at any time later during run.
void main_quit (Xputty *main)
main_quit - destroy all remaining Widget_t's from the main->childlist.
Free all resources which may be allocated between init and quit.
It should be called after main_run()/run_embedded();
Macro Definition Documentation
DEBUG
#define DEBUG 0
Definition at line 53 of file xputty.h.
debug_print
#define debug_print (...) ((void)((DEBUG) ? fprintf(stderr, __VA_ARGS__) : 0))
debug_print - print out state messages when compiled with the -DDEBUG flag
Definition at line 64 of file xputty.h.
IS_UTF8
#define IS_UTF8 (c) (((c)&0xc0)==0xc0)
IS_UTF8 - check if a char contain UTF 8 formated signs.
Definition at line 99 of file xputty.h.
max
#define max (x, y) ((x) < (y) ? (y) : (x))
max - set a minimal value (x) as return value
Definition at line 86 of file xputty.h.
min
#define min (x, y) ((x) < (y) ? (x) : (y))
min - set a maximal value (x) as return value
Definition at line 78 of file xputty.h.
NDEBUG
#define NDEBUG
Definition at line 55 of file xputty.h.
XPUTTY1_H_
#define XPUTTY1_H_
Definition at line 24 of file xputty.h.
Typedef Documentation
Adjustment_t
typedef struct Adjustment_t Adjustment_t
Adjustment_t - Adjustment_t for a Widget_t.
Definition at line 117 of file xputty.h.
Childlist_t
typedef struct Childlist_t Childlist_t
Childlist_t - maintain a Widget_t list of childs for a Widget_t.
Definition at line 111 of file xputty.h.
Widget_t
typedef struct Widget_t Widget_t
Widget_t - the Widget_t base struct.
Definition at line 123 of file xputty.h.
XColor_t
typedef struct XColor_t XColor_t
XColor_t - the Widget_t Color struct.
Definition at line 129 of file xputty.h.
Xputty
typedef struct Xputty Xputty
Xputty - the main struct.It should be declared before any other call to a Xputty function.
Definition at line 136 of file xputty.h.
Function Documentation
main_init()
void main_init (Xputty * main)
main_init - open the Display and init the main->childlist.
Set the bool run to true.
The bool run is used to terminate the main event loop.
main_init() should be called directly after the declaration of Xputty before the first Widget_t get created.
Any Widget_t created afterwards will be added to the main childlist.
The main childlist is used to check if a Widget_t is valid to receive a Event.
Xputty check if a Widget_t is registerd in the main childlist, and only forward events when it found the Widget_t in the list.
When a Widget_t call destroy_widget() any childs of this Widget_t receive a call to destroy_widget() to release there memory, they get removed from the main childlist and finaly the Widget_t itself will be removed from the main childlist as well. On main_quit() any remaining Widget_t from the main childlist will be destroyed, to ensure that we leave the memory clean.
Parameters
*main - pointer to the main Xputty struct
Returns
void
Definition at line 24 of file xputty.c.
{
     main->dpy = XOpenDisplay(0);
     assert(main->dpy);
     main->childlist = (Childlist_t*)malloc(sizeof(Childlist_t));
     assert(main->childlist);
     childlist_init(main->childlist);
     main->color_scheme = (XColor_t*)malloc(sizeof(XColor_t));
     assert(main->color_scheme);
     set_dark_theme(main);
     main->hold_grab = NULL;
     main->run = true;
     main->small_font = 10;
     main->normal_font = 12;
     main->big_font = 16;
 }
References Xputty::big_font, Xputty::childlist, childlist_init(), Xputty::color_scheme, Xputty::dpy, Xputty::hold_grab, Xputty::normal_font, Xputty::run, set_dark_theme(), and Xputty::small_font.
main_quit()
void main_quit (Xputty * main)
main_quit - destroy all remaining Widget_t's from the main->childlist.
Free all resources which may be allocated between init and quit.
It should be called after main_run()/run_embedded();
Parameters
*main - pointer to the main Xputty struct
Returns
void
Definition at line 142 of file xputty.c.
{
     int i = main->childlist->elem-1;
     for(;i>-1;i--) {
         Widget_t *w = main->childlist->childs[i];
         destroy_widget(w, main);
     }
     childlist_destroy(main->childlist);
     free(main->childlist);
     free(main->color_scheme);
     XCloseDisplay(main->dpy);
     debug_print("quit\n");
 }
References Xputty::childlist, childlist_destroy(), Childlist_t::childs, Xputty::color_scheme, debug_print, destroy_widget(), Xputty::dpy, and Childlist_t::elem.
main_run()
void main_run (Xputty * main)
main_run - start the main event loop.
It should be start after your Widget_t's been created.
You could create and destroy additional Widget_t's at any time later during run.
Parameters
*main - pointer to the main Xputty struct
Returns
void
Definition at line 40 of file xputty.c.
{
     Widget_t * wid = main->childlist->childs[0];
     Atom WM_DELETE_WINDOW;
     WM_DELETE_WINDOW = XInternAtom(wid->app->dpy, "WM_DELETE_WINDOW", True);
     XSetWMProtocols(wid->app->dpy, wid->widget, &WM_DELETE_WINDOW, 1);
     XEvent xev;
     int ew;
     while (main->run && (XNextEvent(main->dpy, &xev)>=0)) {
         if (XFilterEvent(&xev, None)) continue;
         ew = childlist_find_widget(main->childlist, xev.xany.window);
         if(ew  >= 0) {
             Widget_t * w = main->childlist->childs[ew];
             w->event_callback(w, &xev, main, NULL);
         }
         switch (xev.type) {
         case ButtonPress:
             if(main->hold_grab != NULL) {
                 Widget_t *view_port = main->hold_grab->childlist->childs[0];
                 bool is_item = False;
                 int i = view_port->childlist->elem-1;
                 for(;i>-1;i--) {
                     Widget_t *w = view_port->childlist->childs[i];
                     if (xev.xbutton.window == w->widget) {
                         is_item = True;
                         break;
                     }
                 }
                 if (xev.xbutton.window == view_port->widget) is_item = True;
                 if (!is_item) {
                     XUngrabPointer(main->dpy,CurrentTime);
                     widget_hide(main->hold_grab);
                     main->hold_grab = NULL;
                 }
             }
             break;
             case ClientMessage:
                 /* delete window event */
                 if (xev.xclient.data.l[0] == (long int)WM_DELETE_WINDOW &&
                         xev.xclient.window == wid->widget) {
                     main->run = false;
                 } else {
                     int i = childlist_find_widget(main->childlist, xev.xclient.window);
                     if(i<1) return;
                     Widget_t *w = main->childlist->childs[i];
                     if(w->flags & HIDE_ON_DELETE) widget_hide(w);
                     else destroy_widget(main->childlist->childs[i],main);
                 }
             break;
         }
     }
 }
References Widget_t::app, Xputty::childlist, Widget_t::childlist, childlist_find_widget(), Childlist_t::childs, destroy_widget(), Xputty::dpy, Childlist_t::elem, Widget_t::event_callback, Widget_t::flags, HIDE_ON_DELETE, Xputty::hold_grab, Xputty::run, Widget_t::widget, and widget_hide().
run_embedded()
void run_embedded (Xputty * main)
run_embedded - the main event loop to run embedded UI's.
It should be start after your Widget_t's been created.
You could create and destroy additional Widget_t's at any time later during run.
Parameters
*main - pointer to the main Xputty struct
Returns
void
Definition at line 95 of file xputty.c.
{
     XEvent xev;
     int ew = -1;
     while (XPending(main->dpy) > 0) {
         XNextEvent(main->dpy, &xev);
         ew = childlist_find_widget(main->childlist, xev.xany.window);
         if(ew  >= 0) {
             Widget_t * w = main->childlist->childs[ew];
             w->event_callback(w, &xev, main, NULL);
         }
         switch (xev.type) {
         case ButtonPress:
             if(main->hold_grab != NULL) {
                 Widget_t *view_port = main->hold_grab->childlist->childs[0];
                 bool is_item = False;
                 int i = view_port->childlist->elem-1;
                 for(;i>-1;i--) {
                     Widget_t *w = view_port->childlist->childs[i];
                     if (xev.xbutton.window == w->widget) {
                         is_item = True;
                         break;
                     }
                 }
                 if (xev.xbutton.window == view_port->widget) is_item = True;
                 if (!is_item) {
                     XUngrabPointer(main->dpy,CurrentTime);
                     widget_hide(main->hold_grab);
                     main->hold_grab = NULL;
                 }
             }
         break;
         case ClientMessage:
             /* delete window event */
             if (xev.xclient.data.l[0] == (long int)XInternAtom(main->dpy, "WM_DELETE_WINDOW", True) ) {
                 int i = childlist_find_widget(main->childlist, xev.xclient.window);
                 if(i<1) return;
                 Widget_t *w = main->childlist->childs[i];
                 if(w->flags & HIDE_ON_DELETE) widget_hide(w);
                 else destroy_widget(w, main);
             }
         break;
         }
     }
 }
References Xputty::childlist, Widget_t::childlist, childlist_find_widget(), Childlist_t::childs, destroy_widget(), Xputty::dpy, Childlist_t::elem, Widget_t::event_callback, Widget_t::flags, HIDE_ON_DELETE, Xputty::hold_grab, Widget_t::widget, and widget_hide().