libxputty: xsavefile-dialoge.c File Reference
xsavefile-dialoge.c File Reference
#include <dirent.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <unistd.h>
#include <libgen.h>
#include "xfile-dialog.h"
#include "xmessage-dialog.h"
Functions
Widget_t * save_file_dialog (Widget_t *w, const char *path, const char *filter)
save_file_dialog - open a non blocking dialog window, to select a file. The path to open the file-selector could be NULL It will open then in $HOME. The filter to use could be NULL, then the file-selector will show all files.
Widget_t * add_save_file_button (Widget_t *parent, int x, int y, int width, int height, const char *path, const char *filter)
add_save_file_button - add a pre-defined button which will pop-up a file dialog when pressed. path and filter will e hand over to the file selector.
Function Documentation
add_save_file_button()
Widget_t* add_save_file_button (Widget_t * parent, int x, int y, int width, int height, const char * path, const char * filter)
add_save_file_button - add a pre-defined button which will pop-up a file dialog when pressed. path and filter will e hand over to the file selector.
Returns
Widget_t* - pointer to the Widget_t struct
Definition at line 534 of file xsavefile-dialoge.c.
{
     FileButton *filebutton = (FileButton*)malloc(sizeof(FileButton));
     filebutton->path = path;
     filebutton->filter = filter;
     filebutton->last_path = NULL;
     filebutton->w = NULL;
     filebutton->is_active = false;
     Widget_t *fbutton = add_image_toggle_button(parent, "", x, y, width, height);
     fbutton->parent_struct = filebutton;
     fbutton->flags |= HAS_MEM;
     widget_get_png(fbutton, LDVAR(directory_open_png));
     fbutton->scale.gravity = CENTER;
     fbutton->func.mem_free_callback = fbutton_mem_free;
     fbutton->func.value_changed_callback = fbutton_callback;
     fbutton->func.dialog_callback = fdialog_response;
     return fbutton;
 }
References add_image_toggle_button(), CENTER, FileButton::filter, Widget_t::flags, Widget_t::func, Resize_t::gravity, HAS_MEM, FileButton::is_active, FileButton::last_path, LDVAR, Func_t::mem_free_callback, Widget_t::parent_struct, FileButton::path, Widget_t::scale, FileButton::w, and widget_get_png().
save_file_dialog()
Widget_t* save_file_dialog (Widget_t * w, const char * path, const char * filter)
save_file_dialog - open a non blocking dialog window, to select a file. The path to open the file-selector could be NULL It will open then in $HOME. The filter to use could be NULL, then the file-selector will show all files.
Returns
Widget_t* - pointer to the Widget_t struct
Definition at line 401 of file xsavefile-dialoge.c.
{
     FileDialog *file_dialog = (FileDialog*)malloc(sizeof(FileDialog));
     file_dialog->fp = (FilePicker*)malloc(sizeof(FilePicker));
     fp_init(file_dialog->fp, (path) ? path : "/");
     file_dialog->parent = w;
     file_dialog->send_clear_func = true;
     file_dialog->icon = NULL;
     file_dialog->w = create_window(w->app, DefaultRootWindow(w->app->dpy), 0, 0, 660, 420);
     file_dialog->w->flags |= HAS_MEM;
     file_dialog->w->parent_struct = file_dialog;
     widget_set_title(file_dialog->w, "File Save");
     file_dialog->w->func.expose_callback = draw_window;
     file_dialog->w->func.key_press_callback = forward_key_press;
     file_dialog->w->func.mem_free_callback = fd_mem_free;
     widget_set_icon_from_png(file_dialog->w,file_dialog->icon,LDVAR(directory_png));
     file_dialog->ct = add_combobox(file_dialog->w, "", 20, 40, 550, 30);
     file_dialog->ct->parent_struct = file_dialog;
     file_dialog->ct->func.value_changed_callback = combo_response;
     file_dialog->ct->func.key_press_callback = forward_key_press;
     file_dialog->sel_dir = add_button(file_dialog->w, "Open", 580, 40, 60, 30);
     file_dialog->sel_dir->parent_struct = file_dialog;
     file_dialog->sel_dir->scale.gravity = CENTER;
     add_tooltip(file_dialog->sel_dir,"Open sub-directory's");
     file_dialog->sel_dir->func.value_changed_callback = open_dir_callback;
     file_dialog->sel_dir->func.key_press_callback = forward_key_press;
     file_dialog->ft = add_listview(file_dialog->w, "", 20, 90, 620, 225);
     file_dialog->ft->parent_struct = file_dialog;
     file_dialog->ft->func.key_press_callback = forward_key_press;
     int ds = fp_get_files(file_dialog->fp,file_dialog->fp->path, 1);
     int set_f = set_files(file_dialog);
     set_dirs(file_dialog);
     combobox_set_active_entry(file_dialog->ct, ds);
     listview_set_active_entry(file_dialog->ft, set_f);
     file_dialog->ft->func.value_changed_callback = file_released_callback;
     file_dialog->text_entry = create_widget(file_dialog->w->app, file_dialog->w, 80, 320, 200, 30);
     memset(file_dialog->text_entry->input_label, 0, 32 * (sizeof file_dialog->text_entry->input_label[0]) );
     file_dialog->text_entry->func.expose_callback = entry_add_text;
     file_dialog->text_entry->func.key_press_callback = entry_get_text;
     file_dialog->text_entry->flags &= ~USE_TRANSPARENCY;
     file_dialog->text_entry->scale.gravity = CENTER;
     file_dialog->w_quit = add_button(file_dialog->w, "Quit", 580, 350, 60, 60);
     file_dialog->w_quit->parent_struct = file_dialog;
     file_dialog->w_quit->scale.gravity = CENTER;
     add_tooltip(file_dialog->w_quit,"Exit File Saver");
     file_dialog->w_quit->func.value_changed_callback = button_quit_callback;
     file_dialog->w_quit->func.key_press_callback = forward_key_press;
     file_dialog->w_okay = add_button(file_dialog->w, "Save", 510, 350, 60, 60);
     file_dialog->w_okay->parent_struct = file_dialog;
     file_dialog->w_okay->scale.gravity = CENTER;
     add_tooltip(file_dialog->w_okay,"Save as selected file");
     file_dialog->w_okay->func.value_changed_callback = button_ok_callback;
     file_dialog->w_okay->func.key_press_callback = forward_key_press;
     file_dialog->set_filter = add_combobox(file_dialog->w, "", 360, 355, 120, 30);
     file_dialog->set_filter->parent_struct = file_dialog;
     combobox_add_entry(file_dialog->set_filter,"all");
     combobox_add_entry(file_dialog->set_filter,"application");
     combobox_add_entry(file_dialog->set_filter,"audio");
     combobox_add_entry(file_dialog->set_filter,"font");
     combobox_add_entry(file_dialog->set_filter,"image");
     combobox_add_entry(file_dialog->set_filter,"text");
     combobox_add_entry(file_dialog->set_filter,"video");
     combobox_add_entry(file_dialog->set_filter,"x-content");
     if(filter !=NULL && strlen(filter))
         combobox_add_entry(file_dialog->set_filter,filter);
     combobox_set_active_entry(file_dialog->set_filter, 0);
     file_dialog->set_filter->func.value_changed_callback = set_filter_callback;
     if(filter !=NULL && strlen(filter))
         combobox_set_active_entry(file_dialog->set_filter, 8);
     add_tooltip(file_dialog->set_filter->childlist->childs[0], "File filter type");
     file_dialog->w_hidden = add_check_button(file_dialog->w, "", 20, 365, 20, 20);
     file_dialog->w_hidden->parent_struct = file_dialog;
     file_dialog->w_hidden->scale.gravity = CENTER;
     add_tooltip(file_dialog->w_hidden,"Show hidden files and folders");
     file_dialog->w_hidden->func.value_changed_callback = button_hidden_callback;
     widget_show_all(file_dialog->w);
     return file_dialog->w;
 }
References Widget_t::app, create_window(), Xputty::dpy, Func_t::expose_callback, Widget_t::flags, FileDialog::fp, fp_init(), Widget_t::func, HAS_MEM, FileDialog::icon, FileDialog::parent, Widget_t::parent_struct, FileDialog::send_clear_func, FileDialog::w, and widget_set_title().