libxputty: xslider_private.c File Reference
xslider_private.c File Reference
#include "xslider_private.h"
Functions
void _pattern_vslider (Widget_t *w, Color_state st, int width)
_pattern_vslider - set pattern for the slider base
void _pattern_hslider (Widget_t *w, Color_state st, int height)
_pattern_hslider - set pattern for the slider base
void _draw_vslider (void *w_, void *user_data)
_draw_vslider - internal draw the slider to the buffer
void _draw_hslider (void *w_, void *user_data)
_draw_hslider - internal draw the slider to the buffer
void _slider_released (void *w_, void *button_, void *user_data)
_slider_released - redraw the slider when button released
Function Documentation
_draw_hslider()
void _draw_hslider (void * w_, void * user_data)
_draw_hslider - internal draw the slider to the buffer
Parameters
*w_ - void pointer to the Widget_t button
*user_data - void pointer to attached user_data
Returns
void
Definition at line 118 of file xslider_private.c.
References _pattern_hslider(), Widget_t::adj, adj_get_state(), Widget_t::adj_x, Widget_t::app, Widget_t::crb, Xputty::dpy, get_color_state(), Widget_t::label, NORMAL_, use_bg_color_scheme(), use_fg_color_scheme(), use_shadow_color_scheme(), use_text_color_scheme(), Adjustment_t::value, and Widget_t::widget.
{
     Widget_t *w = (Widget_t*)w_;
     XWindowAttributes attrs;
     XGetWindowAttributes(w->app->dpy, (Window)w->widget, &attrs);
     int width = attrs.width-2;
     int height = attrs.height-2;
     float center = (float)height/2;
     float upcenter = (float)height;
     if (attrs.map_state != IsViewable) return;
     float sliderstate = adj_get_state(w->adj_x);
     _pattern_hslider(w, get_color_state(w), height);
     cairo_move_to (w->crb, center, center);
     cairo_line_to(w->crb,width-center-10,center);
     cairo_set_line_cap (w->crb,CAIRO_LINE_CAP_ROUND);
     cairo_set_line_width(w->crb,center);
     cairo_stroke(w->crb);
     use_shadow_color_scheme(w, get_color_state(w));
     cairo_move_to (w->crb, center, center);
     cairo_line_to(w->crb,width-center-10,center);
     cairo_set_line_width(w->crb,center/10);
     cairo_stroke(w->crb);
     use_shadow_color_scheme(w, get_color_state(w));
     cairo_arc(w->crb, (center) +
         ((width-10-upcenter) * sliderstate),center, center/2, 0, 2 * M_PI );
     cairo_fill_preserve(w->crb);
     cairo_set_line_width(w->crb,1);
     cairo_stroke(w->crb);
     use_bg_color_scheme(w, get_color_state(w));
     cairo_arc(w->crb, (center) +
         ((width-10-upcenter) * sliderstate),center, center/3, 0, 2 * M_PI );
     cairo_fill_preserve(w->crb);
     use_fg_color_scheme(w, NORMAL_);
     cairo_set_line_width(w->crb,center/15);
     cairo_stroke(w->crb);
     cairo_new_path (w->crb);
     cairo_text_extents_t extents;
     use_text_color_scheme(w, get_color_state(w));
     cairo_set_font_size (w->crb, center/2);
     cairo_select_font_face (w->crb, "Sans", CAIRO_FONT_SLANT_NORMAL,
                                CAIRO_FONT_WEIGHT_BOLD);
     cairo_text_extents(w->crb,w->label , &extents);
     cairo_move_to (w->crb, width/2-extents.width/2, height );
     cairo_show_text(w->crb, w->label);
     cairo_new_path (w->crb);
     char s[64];
     const char* format[] = {"%.1f", "%.2f", "%.3f"};
     if (fabs(w->adj->value)>9.99) {
         snprintf(s, 63,"%d",  (int) w->adj->value);
     } else if (fabs(w->adj->value)>0.99) {
         snprintf(s, 63, format[1-1], w->adj->value);
     } else {
         snprintf(s, 63, format[2-1], w->adj->value);
     }
     cairo_text_extents(w->crb,s , &extents);
     cairo_move_to (w->crb, width/2-extents.width/2, extents.height );
     cairo_show_text(w->crb, s);
     cairo_new_path (w->crb);
 }
_draw_vslider()
void _draw_vslider (void * w_, void * user_data)
_draw_vslider - internal draw the slider to the buffer
Parameters
*w_ - void pointer to the Widget_t button
*user_data - void pointer to attached user_data
Returns
void
Definition at line 47 of file xslider_private.c.
References _pattern_vslider(), Widget_t::adj, adj_get_state(), Widget_t::adj_y, Widget_t::app, Widget_t::crb, Xputty::dpy, get_color_state(), Widget_t::label, NORMAL_, use_bg_color_scheme(), use_fg_color_scheme(), use_shadow_color_scheme(), use_text_color_scheme(), Adjustment_t::value, and Widget_t::widget.
{
     Widget_t *w = (Widget_t*)w_;
     XWindowAttributes attrs;
     XGetWindowAttributes(w->app->dpy, (Window)w->widget, &attrs);
     int width = attrs.width-2;
     int height = attrs.height-2;
     float center = (float)width/2;
     float upcenter = (float)width;
     if (attrs.map_state != IsViewable) return;
     float sliderstate = adj_get_state(w->adj_y);
     _pattern_vslider(w, get_color_state(w), width);
     cairo_move_to (w->crb, center, center);
     cairo_line_to(w->crb,center,height-center-10);
     cairo_set_line_cap (w->crb,CAIRO_LINE_CAP_ROUND);
     cairo_set_line_width(w->crb,center);
     cairo_stroke(w->crb);
     use_shadow_color_scheme(w, get_color_state(w));
     cairo_move_to (w->crb, center, center);
     cairo_line_to(w->crb,center,height-center-10);
     cairo_set_line_width(w->crb,center/10);
     cairo_stroke(w->crb);
     use_shadow_color_scheme(w, get_color_state(w));
     cairo_arc(w->crb,center, (height-center-10) -
         ((height-10-upcenter) * sliderstate), center/2, 0, 2 * M_PI );
     cairo_fill_preserve(w->crb);
     cairo_set_line_width(w->crb,1);
     cairo_stroke(w->crb);
     use_bg_color_scheme(w, get_color_state(w));
     cairo_arc(w->crb,center, (height-center-10) -
         ((height-10-upcenter) * sliderstate), center/3, 0, 2 * M_PI );
     cairo_fill_preserve(w->crb);
     use_fg_color_scheme(w, NORMAL_);
     cairo_set_line_width(w->crb,center/15);
     cairo_stroke(w->crb);
     cairo_new_path (w->crb);
     cairo_text_extents_t extents;
     use_text_color_scheme(w, get_color_state(w));
     cairo_set_font_size (w->crb, center/2);
     cairo_select_font_face (w->crb, "Sans", CAIRO_FONT_SLANT_NORMAL,
                                CAIRO_FONT_WEIGHT_BOLD);
     cairo_text_extents(w->crb,w->label , &extents);
     cairo_move_to (w->crb, center-extents.width/2, height );
     cairo_show_text(w->crb, w->label);
     cairo_new_path (w->crb);
     char s[64];
     const char* format[] = {"%.1f", "%.2f", "%.3f"};
     if (fabs(w->adj_y->value)>9.99) {
         snprintf(s, 63,"%d",  (int) w->adj->value);
     } else if (fabs(w->adj_y->value)>0.99) {
         snprintf(s, 63, format[1-1], w->adj->value);
     } else {
         snprintf(s, 63, format[2-1], w->adj->value);
     }
     cairo_text_extents(w->crb,s , &extents);
     cairo_move_to (w->crb, center-extents.width/2, extents.height );
     cairo_show_text(w->crb, s);
     cairo_new_path (w->crb);
 }
_pattern_hslider()
void _pattern_hslider (Widget_t * w, Color_state st, int width)
_pattern_hslider - set pattern for the slider base
Parameters
*w_ - void pointer to the Widget_t button
st - the Widget_t Color_t mode to use
width - the width of the base
Returns
void
Definition at line 36 of file xslider_private.c.
References Widget_t::app, Colors::base, Widget_t::crb, and get_color_scheme().
{
     Colors *c = get_color_scheme(w->app,st);
     if (!c) return;
     cairo_pattern_t *pat = cairo_pattern_create_linear (2, 2, 2, height);
     cairo_pattern_add_color_stop_rgba(pat, 0.0, c->base[0],  c->base[1], c->base[2],  c->base[3]);
     cairo_pattern_add_color_stop_rgba(pat, 0.5, 0.0, 0.0, 0.0, 0.0);
     cairo_pattern_add_color_stop_rgba(pat, 1.0, c->base[0],  c->base[1], c->base[2],  c->base[3]);
     cairo_set_source(w->crb, pat);
     cairo_pattern_destroy (pat);
 }
_pattern_vslider()
void _pattern_vslider (Widget_t * w, Color_state st, int width)
_pattern_vslider - set pattern for the slider base
Parameters
*w_ - void pointer to the Widget_t button
st - the Widget_t Color_t mode to use
width - the width of the base
Returns
void
Definition at line 25 of file xslider_private.c.
References Widget_t::app, Colors::base, Widget_t::crb, and get_color_scheme().
{
     Colors *c = get_color_scheme(w->app,st);
     if (!c) return;
     cairo_pattern_t *pat = cairo_pattern_create_linear (2, 2, width, 2);
     cairo_pattern_add_color_stop_rgba(pat, 0.0, c->base[0],  c->base[1], c->base[2],  c->base[3]);
     cairo_pattern_add_color_stop_rgba(pat, 0.5, 0.0, 0.0, 0.0, 0.0);
     cairo_pattern_add_color_stop_rgba(pat, 1.0, c->base[0],  c->base[1], c->base[2],  c->base[3]);
     cairo_set_source(w->crb, pat);
     cairo_pattern_destroy (pat);
 }
_slider_released()
void _slider_released (void * w_, void * button_, void * user_data)
_slider_released - redraw the slider when button released
Parameters
*w_ - void pointer to the Widget_t button
*user_data - void pointer to attached user_data
Returns
void
Definition at line 188 of file xslider_private.c.
References expose_widget().
{
     expose_widget(w_);
 }