libxputty: xtooltip_private.h File Reference
xtooltip_private.h File Reference
#include "xtooltip.h"
Macros
#define XTOOLTIP_PRIVATE_H_
Functions
void _get_width (Widget_t *w)
_get_width - get the width of a tooltip text and resize the tooltip widget to match the size
void _draw_tooltip (void *w_, void *user_data)
_draw_tooltip - draw tooltip on expose call
Macro Definition Documentation
XTOOLTIP_PRIVATE_H_
#define XTOOLTIP_PRIVATE_H_
Definition at line 25 of file xtooltip_private.h.
Function Documentation
_draw_tooltip()
void _draw_tooltip (void * w_, void * user_data)
_draw_tooltip - draw tooltip on expose call
Parameters
*w_ - the tooltip to draw
*user_data - attached user_data
Returns
void
show label
Definition at line 34 of file xtooltip_private.c.
References Widget_t::app, Widget_t::crb, Xputty::dpy, get_color_state(), Widget_t::label, use_bg_color_scheme(), use_text_color_scheme(), and Widget_t::widget.
{
     Widget_t *w = (Widget_t*)w_;
     if (!w) return;
     XWindowAttributes attrs;
     XGetWindowAttributes(w->app->dpy, (Window)w->widget, &attrs);
     if (attrs.map_state != IsViewable) return;
     int width = attrs.width;
     int height = attrs.height;
     use_bg_color_scheme(w, get_color_state(w));
     cairo_paint (w->crb);
     cairo_text_extents_t extents;
     /** show label **/
     use_text_color_scheme(w, get_color_state(w));
     cairo_set_font_size (w->crb, 12);
     cairo_select_font_face (w->crb, "Sans", CAIRO_FONT_SLANT_NORMAL,
                                CAIRO_FONT_WEIGHT_BOLD);
     cairo_text_extents(w->crb,w->label , &extents);
     cairo_move_to (w->crb, (width-extents.width)/2., height+5 - extents.height );
     cairo_show_text(w->crb, w->label);
 }
_get_width()
void _get_width (Widget_t * w)
_get_width - get the width of a tooltip text and resize the tooltip widget to match the size
Parameters
*w - the tooltip Widget_t
Returns
void
Definition at line 25 of file xtooltip_private.c.
References Widget_t::app, Widget_t::crb, Xputty::dpy, Widget_t::label, max, and Widget_t::widget.
{
     cairo_text_extents_t extents;
     cairo_set_font_size (w->crb, 12);
     cairo_select_font_face (w->crb, "Sans", CAIRO_FONT_SLANT_NORMAL,
                                CAIRO_FONT_WEIGHT_BOLD);
     cairo_text_extents(w->crb,w->label , &extents);
     XResizeWindow (w->app->dpy, w->widget, max(1, (int)extents.width+40), 25);
 }