libxputty: xtooltip.h File Reference
xtooltip.h File Reference
#include "xputty.h"
Macros
#define XTOOLTIP_H_
Functions
void tooltip_set_text (Widget_t *w, const char *label)
tooltip_set_text - set a (new) text to a tooltip for Widget_t
void add_tooltip (Widget_t *w, const char *label)
add_tooltip - add a tooltip to Widget_t
Widget_t * create_tooltip (Widget_t *parent, int width, int height)
create_tooltip - create a tooltip for a Widget_t
Macro Definition Documentation
XTOOLTIP_H_
#define XTOOLTIP_H_
Definition at line 24 of file xtooltip.h.
Function Documentation
add_tooltip()
void add_tooltip (Widget_t * w, const char * label)
add_tooltip - add a tooltip to Widget_t
Parameters
*w - pointer to the Widget_t request the tooltip
*label - the tooltip text
Returns
void
Definition at line 41 of file xtooltip.c.
{
     Widget_t *wid = create_tooltip(w, 25, 25);
     wid->label = label;
     _get_width(wid);
 }
References _get_width(), create_tooltip(), and Widget_t::label.
create_tooltip()
Widget_t* create_tooltip (Widget_t * parent, int width, int height)
create_tooltip - create a tooltip for a Widget_t
Parameters
*parent - pointer to the Widget_t the tooltip should pop over
width - define the width of the tooltip
height - define the height of the tooltip
Returns
Widget_t* - pointer to the Widget_t button struct
Definition at line 47 of file xtooltip.c.
{
     int x1, y1;
     Window child;
     XTranslateCoordinates( parent->app->dpy, parent->widget, DefaultRootWindow(parent->app->dpy), 0, 0, &x1, &y1, &child );
     Widget_t *wid = create_window(parent->app, DefaultRootWindow(parent->app->dpy), x1+10, y1+10, width, height);
     XSetWindowAttributes attributes;
     attributes.override_redirect = True;
     XChangeWindowAttributes(parent->app->dpy, wid->widget, CWOverrideRedirect, &attributes);
     Atom window_type = XInternAtom(wid->app->dpy, "_NET_WM_WINDOW_TYPE", False);
     Atom window_type_tooltip = XInternAtom(wid->app->dpy, "_NET_WM_WINDOW_TYPE_TOOLTIP", False);
     XChangeProperty(wid->app->dpy, wid->widget, window_type,
         XA_ATOM, 32, PropModeReplace, (unsigned char *) &window_type_tooltip,1 );
     Atom window_state = XInternAtom(wid->app->dpy, "_NET_WM_STATE", False);
     Atom window_state_modal = XInternAtom(wid->app->dpy, "_NET_WM_STATE_MODAL", False);
     XChangeProperty(wid->app->dpy, wid->widget, window_state,
         XA_ATOM, 32, PropModeReplace, (unsigned char *) &window_state_modal, 1);
     XSetTransientForHint(parent->app->dpy,wid->widget,parent->widget);
     wid->flags &= ~USE_TRANSPARENCY;
     wid->func.expose_callback = _draw_tooltip;
     wid->flags |= IS_TOOLTIP;
     parent->flags |= HAS_TOOLTIP;
     wid->scale.gravity = NONE;
     childlist_add_child(parent->childlist, wid);
     return wid;
 }
References _draw_tooltip(), Widget_t::app, Widget_t::childlist, childlist_add_child(), create_window(), Xputty::dpy, Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, HAS_TOOLTIP, IS_TOOLTIP, NONE, Widget_t::scale, USE_TRANSPARENCY, and Widget_t::widget.
tooltip_set_text()
void tooltip_set_text (Widget_t * w, const char * label)
tooltip_set_text - set a (new) text to a tooltip for Widget_t
Parameters
*w - pointer to the Widget_t request the tooltip
*label - the tooltip text
Returns
void
Definition at line 25 of file xtooltip.c.
{
     Widget_t *wid = NULL;
     bool is_tooltip = false;
     int i = 0;
     for(;i<w->childlist->elem;i++) {
         wid = w->childlist->childs[i];
         if (wid->flags & IS_TOOLTIP) {
             wid->label = label;
             _get_width(wid);
             is_tooltip = true;
             break;
         }
     }
     if (!is_tooltip) add_tooltip(w, label);
 }
References _get_width(), add_tooltip(), Widget_t::childlist, Childlist_t::childs, Childlist_t::elem, Widget_t::flags, IS_TOOLTIP, and Widget_t::label.