libxputty: xvaluedisplay_private.c File Reference
xvaluedisplay_private.c File Reference
#include "xvaluedisplay_private.h"
Functions
void _draw_valuedisplay (void *w_, void *user_data)
_draw_valuedisplay - draw a valuedisplay on expose call
Function Documentation
_draw_valuedisplay()
void _draw_valuedisplay (void * w_, void * user_data)
_draw_valuedisplay - draw a valuedisplay on expose call
Parameters
*w_ - The Widget_t contain the valuedisplay
*user_data - attached user_data
Returns
void
Definition at line 25 of file xvaluedisplay_private.c.
{
     Widget_t *w = (Widget_t*)w_;
     if (!w) return;
     XWindowAttributes attrs;
     XGetWindowAttributes(w->app->dpy, (Window)w->widget, &attrs);
     int width = attrs.width-2;
     int height = attrs.height-2;
     if (attrs.map_state != IsViewable) return;
     cairo_rectangle(w->crb,2.0, 2.0, width, height);
     if(w->state==0) {
         cairo_set_line_width(w->crb, 1.0);
         use_shadow_color_scheme(w, NORMAL_);
         cairo_fill_preserve(w->crb);
         use_frame_color_scheme(w, NORMAL_);
     } else if(w->state==1) {
         use_shadow_color_scheme(w, PRELIGHT_);
         cairo_fill_preserve(w->crb);
         cairo_set_line_width(w->crb, 1.5);
         use_frame_color_scheme(w, NORMAL_);
     } else if(w->state==2) {
         use_shadow_color_scheme(w, SELECTED_);
         cairo_fill_preserve(w->crb);
         cairo_set_line_width(w->crb, 1.0);
         use_frame_color_scheme(w, SELECTED_);
     } else if(w->state==3) {
         use_shadow_color_scheme(w, ACTIVE_);
         cairo_fill_preserve(w->crb);
         cairo_set_line_width(w->crb, 1.0);
         use_frame_color_scheme(w, ACTIVE_);
     } else if(w->state==4) {
         use_shadow_color_scheme(w, INSENSITIVE_);
         cairo_fill_preserve(w->crb);
         cairo_set_line_width(w->crb, 1.0);
         use_frame_color_scheme(w, INSENSITIVE_);
     }
     cairo_stroke(w->crb);
     cairo_rectangle(w->crb,4.0, 4.0, width, height);
     cairo_stroke(w->crb);
     cairo_rectangle(w->crb,3.0, 3.0, width, height);
     cairo_stroke(w->crb);
     cairo_text_extents_t extents;
     char s[64];
     const char* format[] = {"%.1f ", "%.2f ", "%. Hz"};
     float value = adj_get_value(w->adj);
     snprintf(s, 63, format[2-1], value);
     use_text_color_scheme(w, get_color_state(w));
     float font_size = w->app->normal_font/w->scale.ascale;
     cairo_set_font_size (w->crb, font_size);
     cairo_text_extents(w->crb,s , &extents);
     cairo_move_to (w->crb, (width-extents.width)*0.5, (height+extents.height)*0.55);
     cairo_show_text(w->crb, s);
     cairo_new_path (w->crb);
 }
References ACTIVE_, Widget_t::adj, adj_get_value(), Widget_t::app, Resize_t::ascale, Widget_t::crb, Xputty::dpy, get_color_state(), INSENSITIVE_, NORMAL_, Xputty::normal_font, PRELIGHT_, Widget_t::scale, SELECTED_, Widget_t::state, use_frame_color_scheme(), use_shadow_color_scheme(), use_text_color_scheme(), and Widget_t::widget.