libxputty: xvaluedisplay.h File Reference
xvaluedisplay.h File Reference
#include "xputty.h"
Macros
#define XVALUEDISPLAY_H_
Functions
Widget_t * add_valuedisplay (Widget_t *parent, const char *label, int x, int y, int width, int height)
add_valuedisplay - add a valuedisplay widget to a Widget_t
Macro Definition Documentation
XVALUEDISPLAY_H_
#define XVALUEDISPLAY_H_
Definition at line 24 of file xvaluedisplay.h.
Function Documentation
add_valuedisplay()
Widget_t* add_valuedisplay (Widget_t * parent, const char * label, int x, int y, int width, int height)
add_valuedisplay - add a valuedisplay widget to a Widget_t
Parameters
*parent - pointer to the Widget_t request the valuedisplay
*label - Label to show on the valuedisplay
x,y,width,height - the position/geometry to create the valuedisplay
Returns
Widget_t* - pointer to the Widget_t valuedisplay struct
Definition at line 26 of file xvaluedisplay.c.
{
     Widget_t *wid = create_widget(parent->app, parent, x, y, width, height);
     wid->label = label;
     wid->adj_y = add_adjustment(wid,0.0, 0.0, 0.0, 1.0, 0.01, CL_CONTINUOS);
     wid->adj = wid->adj_y;
     wid->scale.gravity = CENTER;
     wid->func.enter_callback = transparent_draw;
     wid->func.leave_callback = transparent_draw;
     wid->func.expose_callback = _draw_valuedisplay;
     return wid;
 }
References _draw_valuedisplay(), add_adjustment(), Widget_t::adj, Widget_t::adj_y, Widget_t::app, CENTER, CL_CONTINUOS, create_widget(), Func_t::enter_callback, Func_t::expose_callback, Widget_t::func, Resize_t::gravity, Widget_t::label, Func_t::leave_callback, Widget_t::scale, and transparent_draw().