libxputty: xwidget.c File Reference
xwidget.c File Reference
#include "xwidget.h"
#include "xwidget_private.h"
Functions
int key_mapping (Display *dpy, XKeyEvent *xkey)
_key_mapping - modifier key's mapped to a integer value
void destroy_widget (Widget_t *w, Xputty *main)
destroy_widget - destroy a widget
When a Widget_t receive a destroy_widget() call, it will propagate that to all childs in it's Childlist_t. So all childs get destroyed before the Widget_t itself close.
void configure_event (void *w_, void *user_data)
void widget_reset_scale (Widget_t *w)
widget_reset_scale - used to reset scaling mode after a image surface is drawn to the Widget_t surface with widget_set_scale()
void widget_set_scale (Widget_t *w)
widget_set_scale - set scaling mode to scale a image surface to the size of the Widget_t surface
Widget_t * create_window (Xputty *app, Window win, int x, int y, int width, int height)
*create_window - create a Window
You need to create as least minimun one Window to get started.
The first created Window is the top_level_widget()
A Window could be created on the DefaultRootWindow() or embeded into a other XWindow
Widget_t * create_widget (Xputty *app, Widget_t *parent, int x, int y, int width, int height)
*create_widget - create a widget
A Widget_t could only be created as child of a other Widget_t
To create a Widget_t you need to create a Widget_t with create_window() before.
void connect_func (void(**event)(), void(*handler)())
connect_func - connect a event with a handler without type check. For supported events see: Func_t
void signal_connect_func (Widget_t *w, EventType type, void(*handler)())
signal_connect_func - connect a event with a handler by EventType identifier, without type check
You must ensure that the handler coresponde to the event type
check EventType for more information
void widget_set_title (Widget_t *w, const char *title)
widget_set_title - set window title for a Widget_t
void widget_show (Widget_t *w)
widget_show - map/show widget
void widget_hide (Widget_t *w)
widget_hide - unmap/hide a Widget_t
void widget_show_all (Widget_t *w)
widget_show_all - map/show Widget_t with all childs
void pop_widget_show_all (Widget_t *w)
pop_widget_show_all - map/show popup widget with all it's childs
void show_tooltip (Widget_t *wid)
show_tooltip - check if a Widget_t have a tooltip, and show it, if a tooltip is available.
void hide_tooltip (Widget_t *wid)
hide_tooltip - check if a Widget_t have a tooltip, and hide it, if a tooltip is mapped.
Widget_t * get_toplevel_widget (Xputty *main)
*get_toplevel_widget - get pointer to the top level Widget_t
void expose_widget (Widget_t *w)
expose_widgets - send a expose event (EXPOSE) to a Widget_t
void transparent_draw (void *w_, void *user_data)
transparent_draw - copy parent surface to child surface
you usaualy didn't need to call this, it's used automaticaly when a Widget_t have set the flag USE_TRANSPARENCY
this is the default setting for Widget_t
void widget_event_loop (void *w_, void *event, Xputty *main, void *user_data)
widget_event_loop - the internal widget event loop
void send_configure_event (Widget_t *w, int x, int y, int width, int height)
send_configure_event - send a ConfigureNotify to Widget_t
used to resize a Widget_t
void send_button_press_event (Widget_t *w)
send_button_press_event - send ButtonPress event to Widget_t
simulate a BUTTON_PRESS Event
void send_button_release_event (Widget_t *w)
send_button_release_event - send ButtonRelease event to Widget_t
simulate a BUTTON_RELEASE Event
void send_systray_message (Widget_t *w)
send_systray_message - request a systray icon for Widget_t
currently not working
void quit (Widget_t *w)
quit - exit the main loop
void quit_widget (Widget_t *w)
quit_widget - remove a widget from the processing loop
Function Documentation
configure_event()
void configure_event (void * w_, void * user_data)
Definition at line 111 of file xwidget.c.
References _resize_childs(), _resize_surface(), Widget_t::app, Resize_t::ascale, Resize_t::cscale_x, Resize_t::cscale_y, debug_print, Xputty::dpy, Widget_t::height, Resize_t::init_height, Resize_t::init_width, Resize_t::rcscale_x, Resize_t::rcscale_y, Widget_t::scale, Resize_t::scale_x, Resize_t::scale_y, Widget_t::widget, and Widget_t::width.
{
     Widget_t *wid = (Widget_t*)w_;
     XWindowAttributes attrs;
     XGetWindowAttributes(wid->app->dpy, (Window)wid->widget, &attrs);
     if (wid->width != attrs.width || wid->height != attrs.height) {
         wid->scale.scale_x    = (float)wid->scale.init_width - attrs.width;
         wid->scale.scale_y    = (float)wid->scale.init_height - attrs.height;
         wid->scale.cscale_x   = (float)((float)wid->scale.init_width/(float)attrs.width);
         wid->scale.cscale_y   = (float)((float)wid->scale.init_height/(float)attrs.height);
         wid->scale.rcscale_x   = (float)((float)attrs.width/(float)wid->scale.init_width);
         wid->scale.rcscale_y   = (float)((float)attrs.height/(float)wid->scale.init_height);
         wid->scale.ascale     = wid->scale.cscale_x < wid->scale.cscale_y ?
                                 wid->scale.cscale_y : wid->scale.cscale_x;
         _resize_surface(wid, attrs.width, attrs.height);
         debug_print("Widget_t configure callback width %i height %i\n", attrs.width, attrs.height);
         _resize_childs(wid);
     }
 }
connect_func()
void connect_func (void(**)() event, void(*)() handler)
connect_func - connect a event with a handler without type check. For supported events see: Func_t
Parameters
**event - the event to connect
*handler - the handler to handle the event
Returns
void
Definition at line 352 of file xwidget.c.
References debug_print.
{
     debug_print("address of a is: %p\n", (void*)event);
     debug_print("address of b is: %p\n", (void*)handler);
     *event = handler;
     debug_print("address of a is: %p\n", (void*)(*event));
 }
create_widget()
Widget_t* create_widget (Xputty * app, Widget_t * win, int x, int y, int width, int height)
*create_widget - create a widget
A Widget_t could only be created as child of a other Widget_t
To create a Widget_t you need to create a Widget_t with create_window() before.
Parameters
*app - pointer to the Xputty *main struct to use
*parent - pointer to the Parrent Widget_t
x,y,width,height - the position/geometry to create the widget
Returns
Widget_t* - pointer to the Widget_t struct
Definition at line 250 of file xwidget.c.
References _dummy1_callback(), _dummy_callback(), Widget_t::adj, Func_t::adj_callback, Widget_t::adj_x, Widget_t::adj_y, Widget_t::app, Resize_t::ascale, Widget_t::buffer, Func_t::button_press_callback, Func_t::button_release_callback, CENTER, Xputty::childlist, Widget_t::childlist, childlist_add_child(), childlist_init(), Func_t::configure_callback, configure_event(), Func_t::configure_notify_callback, Widget_t::cr, Widget_t::crb, Resize_t::cscale_x, Resize_t::cscale_y, Widget_t::data, debug_print, Func_t::dialog_callback, Xputty::dpy, Func_t::enter_callback, Widget_t::event_callback, Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, Widget_t::height, Widget_t::image, Resize_t::init_height, Resize_t::init_width, Resize_t::init_x, Resize_t::init_y, IS_WIDGET, Func_t::key_press_callback, Func_t::key_release_callback, Widget_t::label, Func_t::leave_callback, Func_t::map_notify_callback, Func_t::mem_free_callback, Func_t::motion_callback, NO_AUTOREPEAT, Widget_t::parent, Widget_t::parent_struct, Resize_t::rcscale_x, Resize_t::rcscale_y, Widget_t::scale, Resize_t::scale_x, Resize_t::scale_y, Widget_t::state, Widget_t::surface, transparent_draw(), USE_TRANSPARENCY, Func_t::user_callback, Func_t::value_changed_callback, Widget_t::widget, widget_event_loop(), Widget_t::width, Widget_t::x, Widget_t::xic, Widget_t::xim, and Widget_t::y.
{
     Widget_t *w = (Widget_t*)malloc(sizeof(Widget_t));
     assert(w != NULL);
     debug_print("assert(w)\n");
     XSetWindowAttributes attributes;
     attributes.save_under = True;
     attributes.override_redirect = True;
     long event_mask = StructureNotifyMask|ExposureMask|KeyPressMask
                     |EnterWindowMask|LeaveWindowMask|ButtonReleaseMask
                     |ButtonPressMask|Button1MotionMask;
     w->widget = XCreateWindow(app->dpy, parent->widget , x, y, width, height, 0,
                             CopyFromParent, InputOutput, CopyFromParent,
                             CopyFromParent|CWOverrideRedirect, &attributes);
     debug_print("XCreateWindow\n");
     XSetLocaleModifiers("");
     w->xim = XOpenIM(app->dpy, 0, 0, 0);
     if(!w->xim){
         XSetLocaleModifiers("@im=none");
         w->xim = XOpenIM(app->dpy, 0, 0, 0);
     }
     w->xic = XCreateIC(w->xim, XNInputStyle, XIMPreeditNothing | XIMStatusNothing,
                     XNClientWindow, w->widget, XNFocusWindow,  w->widget, NULL);
     XSetICFocus(w->xic);
     XSelectInput(app->dpy, w->widget, event_mask);
     w->surface =  cairo_xlib_surface_create (app->dpy, w->widget,
                   DefaultVisual(app->dpy, DefaultScreen(app->dpy)), width, height);
     w->cr = cairo_create(w->surface);
     w->buffer = cairo_surface_create_similar (w->surface,
                         CAIRO_CONTENT_COLOR_ALPHA, width, height);
     w->crb = cairo_create (w->buffer);
     w->image = NULL;
     w->flags = IS_WIDGET | USE_TRANSPARENCY;
     w->flags &= ~NO_AUTOREPEAT;
     w->app = app;
     w->parent = parent;
     w->parent_struct = NULL;
     w->label = NULL;
     w->state = 0;
     w->data = 0;
     w->x = x;
     w->y = y;
     w->width = width;
     w->height = height;
     w->scale.gravity = CENTER;
     w->scale.init_width = width;
     w->scale.init_height = height;
     w->scale.init_x   = x;
     w->scale.init_y   = y;
     w->scale.scale_x  = 0.0;
     w->scale.scale_y  = 0.0;
     w->scale.cscale_x = 1.0;
     w->scale.cscale_y = 1.0;
     w->scale.rcscale_x = 1.0;
     w->scale.rcscale_y = 1.0;
     w->scale.ascale   = 1.0;
     w->adj_x = NULL;
     w->adj_y = NULL;
     w->adj   = NULL;
     w->childlist = (Childlist_t*)malloc(sizeof(Childlist_t));
     assert(w->childlist != NULL);
     childlist_init(w->childlist);
     childlist_add_child(parent->childlist, w);
     w->event_callback = widget_event_loop;
     w->func.expose_callback = _dummy_callback;
     w->func.configure_callback = configure_event;
     w->func.button_press_callback = _dummy1_callback;
     w->func.button_release_callback = _dummy1_callback;
     w->func.motion_callback = _dummy1_callback;
     w->func.adj_callback = transparent_draw;
     w->func.value_changed_callback = _dummy_callback;
     w->func.key_press_callback = _dummy1_callback;
     w->func.key_release_callback = _dummy1_callback;
     w->func.enter_callback = _dummy_callback;
     w->func.leave_callback = _dummy_callback;
     w->func.user_callback = _dummy_callback;
     w->func.mem_free_callback = _dummy_callback;
     w->func.configure_notify_callback = _dummy_callback;
     w->func.map_notify_callback = _dummy_callback;
     w->func.dialog_callback = _dummy_callback;
     childlist_add_child(app->childlist,w);
     //XMapWindow(app->dpy, w->widget);
     debug_print("size of Widget_t = %ld\n", sizeof(struct Widget_t));
     return w;
 }
create_window()
Widget_t* create_window (Xputty * app, Window win, int x, int y, int width, int height)
*create_window - create a Window
You need to create as least minimun one Window to get started.
The first created Window is the top_level_widget()
A Window could be created on the DefaultRootWindow() or embeded into a other XWindow
Parameters
*app - pointer to the Xputty *main struct to use
win - pointer to the Parrent Window (may be Root)
x,y,width,height - the position/geometry to create the window
Returns
Widget_t * - pointer to the Widget_t struct
Definition at line 141 of file xwidget.c.
References _dummy1_callback(), _dummy_callback(), Widget_t::adj, Func_t::adj_callback, Widget_t::adj_x, Widget_t::adj_y, Widget_t::app, Resize_t::ascale, Widget_t::buffer, Func_t::button_press_callback, Func_t::button_release_callback, CENTER, Xputty::childlist, Widget_t::childlist, childlist_add_child(), childlist_init(), Func_t::configure_callback, configure_event(), Func_t::configure_notify_callback, Widget_t::cr, Widget_t::crb, Resize_t::cscale_x, Resize_t::cscale_y, Widget_t::data, debug_print, Func_t::dialog_callback, Xputty::dpy, Func_t::enter_callback, Widget_t::event_callback, Func_t::expose_callback, Widget_t::flags, Widget_t::func, Resize_t::gravity, Widget_t::height, Widget_t::image, Resize_t::init_height, Resize_t::init_width, Resize_t::init_x, Resize_t::init_y, IS_WINDOW, Func_t::key_press_callback, Func_t::key_release_callback, Widget_t::label, Func_t::leave_callback, Func_t::map_notify_callback, Func_t::mem_free_callback, Func_t::motion_callback, NO_AUTOREPEAT, Widget_t::parent, Widget_t::parent_struct, Resize_t::rcscale_x, Resize_t::rcscale_y, Widget_t::scale, Resize_t::scale_x, Resize_t::scale_y, Widget_t::state, Widget_t::surface, transparent_draw(), Func_t::user_callback, Func_t::value_changed_callback, Widget_t::widget, widget_event_loop(), Widget_t::width, Widget_t::x, Widget_t::xic, Widget_t::xim, and Widget_t::y.
{
     Widget_t *w = (Widget_t*)malloc(sizeof(Widget_t));
     assert(w != NULL);
     debug_print("assert(w)\n");
     XSetWindowAttributes attributes;
     attributes.save_under = True;
     attributes.override_redirect = 0;
     long event_mask = StructureNotifyMask|ExposureMask|KeyPressMask
                     |EnterWindowMask|LeaveWindowMask|ButtonReleaseMask
                     |ButtonPressMask|Button1MotionMask;
     w->widget = XCreateWindow(app->dpy, win , x, y, width, height, 0,
                             CopyFromParent, InputOutput, CopyFromParent,
                             CopyFromParent, &attributes);
     debug_print("XCreateWindow\n");
     XSetLocaleModifiers("");
     w->xim = XOpenIM(app->dpy, 0, 0, 0);
     if(!w->xim){
         XSetLocaleModifiers("@im=none");
         w->xim = XOpenIM(app->dpy, 0, 0, 0);
     }
     w->xic = XCreateIC(w->xim, XNInputStyle, XIMPreeditNothing | XIMStatusNothing,
                     XNClientWindow, w->widget, XNFocusWindow,  w->widget, NULL);
     XSetICFocus(w->xic);
     XSelectInput(app->dpy, w->widget, event_mask);
     XSizeHints* win_size_hints;
     win_size_hints = XAllocSizeHints();
     win_size_hints->flags =  PMinSize|PWinGravity;
     win_size_hints->min_width = width/2;
     win_size_hints->min_height = height/2;
     win_size_hints->win_gravity = CenterGravity;
     XSetWMNormalHints(app->dpy, w->widget, win_size_hints);
     XFree(win_size_hints);
     w->surface =  cairo_xlib_surface_create (app->dpy, w->widget,
                   DefaultVisual(app->dpy, DefaultScreen(app->dpy)), width, height);
     w->cr = cairo_create(w->surface);
     w->buffer = cairo_surface_create_similar (w->surface,
                         CAIRO_CONTENT_COLOR_ALPHA, width, height);
     w->crb = cairo_create (w->buffer);
     w->image = NULL;
     w->flags = IS_WINDOW;
     w->flags &= ~NO_AUTOREPEAT;
     w->app = app;
     w->parent = &win;
     w->parent_struct = NULL;
     w->label = NULL;
     w->state = 0;
     w->data = 0;
     w->x = x;
     w->y = y;
     w->width = width;
     w->height = height;
     w->scale.init_x = x;
     w->scale.init_y = y;
     w->scale.init_width = width;
     w->scale.init_height = height;
     w->scale.scale_x  = 0.0;
     w->scale.scale_y  = 0.0;
     w->scale.cscale_x = 1.0;
     w->scale.cscale_y = 1.0;
     w->scale.rcscale_x = 1.0;
     w->scale.rcscale_y = 1.0;
     w->scale.ascale   = 1.0;
     w->scale.gravity  = CENTER;
     w->adj_x = NULL;
     w->adj_y = NULL;
     w->adj   = NULL;
     w->childlist = (Childlist_t*)malloc(sizeof(Childlist_t));
     assert(w->childlist != NULL);
     childlist_init(w->childlist);
     w->event_callback = widget_event_loop;
     w->func.expose_callback = _dummy_callback;
     w->func.configure_callback = configure_event;
     w->func.button_press_callback = _dummy1_callback;
     w->func.button_release_callback = _dummy1_callback;
     w->func.motion_callback = _dummy1_callback;
     w->func.adj_callback = transparent_draw;
     w->func.value_changed_callback = _dummy_callback;
     w->func.key_press_callback = _dummy1_callback;
     w->func.key_release_callback = _dummy1_callback;
     w->func.enter_callback = _dummy_callback;
     w->func.leave_callback = _dummy_callback;
     w->func.user_callback = _dummy_callback;
     w->func.mem_free_callback = _dummy_callback;
     w->func.configure_notify_callback = _dummy_callback;
     w->func.map_notify_callback = _dummy_callback;
     w->func.dialog_callback = _dummy_callback;
     childlist_add_child(app->childlist,w);
     //XMapWindow(app->dpy, w->widget);
     debug_print("size of Func_t = %lu\n", sizeof(w->func)/sizeof(void*));
     return w;
 }
destroy_widget()
void destroy_widget (Widget_t * w, Xputty * main)
destroy_widget - destroy a widget
When a Widget_t receive a destroy_widget() call, it will propagate that to all childs in it's Childlist_t. So all childs get destroyed before the Widget_t itself close.
Parameters
*w - pointer to the Widget_t sending the request
*main - pointer to main struct
Returns
void
Definition at line 71 of file xwidget.c.
References Widget_t::adj_x, Widget_t::adj_y, Widget_t::app, Widget_t::buffer, Xputty::childlist, Widget_t::childlist, childlist_destroy(), childlist_find_child(), childlist_has_child(), childlist_remove_child(), Childlist_t::childs, Widget_t::cr, Widget_t::crb, delete_adjustment(), Xputty::dpy, Widget_t::flags, Widget_t::func, HAS_MEM, Widget_t::image, IS_WIDGET, Func_t::mem_free_callback, Widget_t::parent, quit(), Xputty::run, Widget_t::surface, Widget_t::widget, Widget_t::xic, and Widget_t::xim.
{
     int count = childlist_find_child(main->childlist, w);
     if (count == 0 && main->run == true) {
         quit(w);
     } else if(childlist_find_child(main->childlist, w)>=0) {
         if(w->flags & HAS_MEM) {
             w->func.mem_free_callback(w, NULL);
         }
         childlist_remove_child(main->childlist, w);
         int ch = childlist_has_child(w->childlist);
         if (ch) {
             int i = ch;
             for(;i>0;i--) {
                 destroy_widget(w->childlist->childs[i-1],main);
             }
             destroy_widget(w,main);
         }
         if(w->flags & IS_WIDGET) {
             Widget_t *p = (Widget_t *) w->parent;
             childlist_remove_child(p->childlist, w);
         }
         delete_adjustment(w->adj_x);
         delete_adjustment(w->adj_y);
         childlist_destroy(w->childlist);
         cairo_surface_destroy(w->image);
         cairo_destroy(w->crb);
         cairo_surface_destroy(w->buffer);
         cairo_destroy(w->cr);
         cairo_surface_destroy(w->surface);
         XDestroyIC(w->xic);
         XCloseIM(w->xim);
         XUnmapWindow(w->app->dpy, w->widget);
         XDestroyWindow(w->app->dpy, w->widget);
         free(w->childlist);
         free(w);
         w = NULL;
     }
 }
expose_widget()
void expose_widget (Widget_t * w)
expose_widgets - send a expose event (EXPOSE) to a Widget_t
Parameters
w - the Widget_t to send the event to
Returns
void
Definition at line 487 of file xwidget.c.
References Widget_t::app, Xputty::dpy, and Widget_t::widget.
{
     XEvent exp;
     memset(&exp, 0, sizeof(exp));
     exp.type = Expose;
     exp.xexpose.window = w->widget;
     XSendEvent(w->app->dpy, w->widget, False, ExposureMask, (XEvent *)&exp);
 }
get_toplevel_widget()
Widget_t* get_toplevel_widget (Xputty * main)
*get_toplevel_widget - get pointer to the top level Widget_t
Parameters
*main - pointer to the main Xputty struct
Returns
void
Definition at line 483 of file xwidget.c.
References Xputty::childlist, and Childlist_t::childs.
{
     return  main->childlist->childs[0];
 }
hide_tooltip()
void hide_tooltip (Widget_t * wid)
hide_tooltip - check if a Widget_t have a tooltip, and hide it, if a tooltip is mapped.
Parameters
*wid - pointer to the Widget_t receiving the event
Returns
void
Definition at line 472 of file xwidget.c.
References Widget_t::childlist, Childlist_t::childs, Childlist_t::elem, Widget_t::flags, IS_TOOLTIP, and widget_hide().
{
     int i = 0;
     for(;i<wid->childlist->elem;i++) {
         Widget_t *w = wid->childlist->childs[i];
         if (w->flags & IS_TOOLTIP) {
             widget_hide(w);
             break;
         }
     }
 }
key_mapping()
int key_mapping (Display * dpy, XKeyEvent * xkey)
_key_mapping - modifier key's mapped to a integer value
Parameters
*dpy - pointer to the Display in use
*xkey - the key to map
Returns
int - value (1-10) or 0 when not mapped
Definition at line 26 of file xwidget.c.
{
     if (xkey->keycode == XKeysymToKeycode(dpy,XK_Tab))
         return (xkey->state == ShiftMask) ? 1 : 2;
     else if (xkey->keycode == XKeysymToKeycode(dpy,XK_Up))
         return 3;
     else if (xkey->keycode == XKeysymToKeycode(dpy,XK_Right))
         return 4;
     else if (xkey->keycode == XKeysymToKeycode(dpy,XK_Down))
         return 5;
     else if (xkey->keycode == XKeysymToKeycode(dpy,XK_Left))
         return 6;
     else if (xkey->keycode == XKeysymToKeycode(dpy,XK_Home))
         return 7;
     else if (xkey->keycode == XKeysymToKeycode(dpy,XK_Insert))
         return 8;
     else if (xkey->keycode == XKeysymToKeycode(dpy,XK_End))
         return 9;
     else if (xkey->keycode == XKeysymToKeycode(dpy,XK_Return))
         return 10;
     else if (xkey->keycode == XKeysymToKeycode(dpy,XK_BackSpace))
         return 11;
     // keypad
     else if (xkey->keycode == XKeysymToKeycode(dpy,XK_KP_Subtract))
         return 1;
     else if (xkey->keycode == XKeysymToKeycode(dpy,XK_KP_Add))
         return 2;
     else if (xkey->keycode == XKeysymToKeycode(dpy,XK_KP_Up))
         return 3;
     else if (xkey->keycode == XKeysymToKeycode(dpy,XK_KP_Right))
         return 4;
     else if (xkey->keycode == XKeysymToKeycode(dpy,XK_KP_Down))
         return 5;
     else if (xkey->keycode == XKeysymToKeycode(dpy,XK_KP_Left))
         return 6;
     else if (xkey->keycode == XKeysymToKeycode(dpy,XK_KP_Home))
         return 7;
     else if (xkey->keycode == XKeysymToKeycode(dpy,XK_KP_Insert))
         return 8;
     else if (xkey->keycode == XKeysymToKeycode(dpy,XK_KP_End))
         return 9;
     else if (xkey->keycode == XKeysymToKeycode(dpy,XK_KP_Enter))
         return 10;
     else return 0;
 }
pop_widget_show_all()
void pop_widget_show_all (Widget_t * w)
pop_widget_show_all - map/show popup widget with all it's childs
Parameters
*w - pointer to the Widget_t to map
Returns
void
Definition at line 444 of file xwidget.c.
References Widget_t::app, Widget_t::childlist, Childlist_t::childs, Xputty::dpy, Childlist_t::elem, Widget_t::func, Func_t::map_notify_callback, and Widget_t::widget.
{
     w->func.map_notify_callback(w, NULL);
     XMapWindow(w->app->dpy, w->widget);
     int i=0;
     for(;i<w->childlist->elem;i++) {
         pop_widget_show_all(w->childlist->childs[i]);
     }
 }
quit()
void quit (Widget_t * w)
quit - exit the main loop
Parameters
*w - pointer to the Widget_t sending the request
Returns
void
Definition at line 717 of file xwidget.c.
References Widget_t::app, Xputty::dpy, get_toplevel_widget(), and Widget_t::widget.
{
     Atom WM_DELETE_WINDOW = XInternAtom(w->app->dpy, "WM_DELETE_WINDOW", True);
     XClientMessageEvent xevent;
     xevent.type = ClientMessage;
     xevent.message_type = WM_DELETE_WINDOW;
     xevent.display = w->app->dpy;
     xevent.window = get_toplevel_widget(w->app)->widget;
     xevent.format = 16;
     xevent.data.l[0] = WM_DELETE_WINDOW;
     XSendEvent(w->app->dpy, w->widget, 0, 0, (XEvent *)&xevent);
 }
quit_widget()
void quit_widget (Widget_t * w)
quit_widget - remove a widget from the processing loop
Parameters
*w - pointer to the Widget_t sending the request
Returns
void
Definition at line 729 of file xwidget.c.
References Widget_t::app, Xputty::dpy, and Widget_t::widget.
{
     Atom QUIT_WIDGET = XInternAtom(w->app->dpy, "WIDGET_DESTROY", False);
     XClientMessageEvent xevent;
     xevent.type = ClientMessage;
     xevent.message_type = QUIT_WIDGET;
     xevent.display = w->app->dpy;
     xevent.window = w->widget;
     xevent.format = 16;
     xevent.data.l[0] = 1;
     XSendEvent(w->app->dpy, w->widget, 0, 0, (XEvent *)&xevent);
 }
send_button_press_event()
void send_button_press_event (Widget_t * w)
send_button_press_event - send ButtonPress event to Widget_t
simulate a BUTTON_PRESS Event
Parameters
*w - pointer to the Widget_t to send the notify
Returns
void
Definition at line 650 of file xwidget.c.
References Widget_t::app, Xputty::dpy, and Widget_t::widget.
{
     XEvent event;
     memset(&event, 0, sizeof(XEvent));
     XWindowAttributes attr;
     XGetWindowAttributes(w->app->dpy, w->widget, &attr);
     event.type = ButtonPress;
     event.xbutton.same_screen = true;
     event.xbutton.root = None;
     event.xbutton.window = w->widget;
     event.xbutton.subwindow = None;
     event.xbutton.x = 1;
     event.xbutton.y = 1;
     event.xbutton.x_root = attr.x;
     event.xbutton.y_root = attr.y;
     event.xbutton.state = 0;
     event.xbutton.button = Button1;
     XSendEvent(w->app->dpy, PointerWindow, True, ButtonPressMask, &event);
 }
send_button_release_event()
void send_button_release_event (Widget_t * w)
send_button_release_event - send ButtonRelease event to Widget_t
simulate a BUTTON_RELEASE Event
Parameters
*w - pointer to the Widget_t to send the notify
Returns
void
Definition at line 670 of file xwidget.c.
References Widget_t::app, Xputty::dpy, and Widget_t::widget.
{
     XEvent event;
     memset(&event, 0, sizeof(XEvent));
     XWindowAttributes attr;
     XGetWindowAttributes(w->app->dpy, w->widget, &attr);
     event.type = ButtonRelease;
     event.xbutton.same_screen = true;
     event.xbutton.root = None;
     event.xbutton.window = w->widget;
     event.xbutton.subwindow = None;
     event.xbutton.x = 1;
     event.xbutton.y = 1;
     event.xbutton.x_root = attr.x;
     event.xbutton.y_root = attr.y;
     event.xbutton.state = 0;
     event.xbutton.button = Button1;
     XSendEvent(w->app->dpy, PointerWindow, True, ButtonReleaseMask, &event);
 }
send_configure_event()
void send_configure_event (Widget_t * w, int x, int y, int width, int height)
send_configure_event - send a ConfigureNotify to Widget_t
used to resize a Widget_t
Parameters
*w - pointer to the Widget_t to send the notify
x,y - the new Widget_t position
width,height - the new Widget_t size
Returns
void
Definition at line 632 of file xwidget.c.
References Widget_t::app, Xputty::dpy, and Widget_t::widget.
{
     XConfigureEvent notify;
     memset(&notify, 0, sizeof(notify));
     notify.type = ConfigureNotify;
     notify.display = w->app->dpy;
     notify.send_event = True;
     notify.event = w->widget;
     notify.window = w->widget;
     notify.x = x;
     notify.y = y;
     notify.width = width;
     notify.height = height;
     notify.border_width = 0;
     notify.above = None;
     notify.override_redirect = 1;
     XSendEvent( w->app->dpy, w->widget, true, StructureNotifyMask, (XEvent*)&notify );
 }
send_systray_message()
void send_systray_message (Widget_t * w)
send_systray_message - request a systray icon for Widget_t
currently not working
Parameters
*w - pointer to the Widget_t to send the notify
Returns
void
Definition at line 690 of file xwidget.c.
References Widget_t::app, Xputty::dpy, SYSTEM_TRAY_REQUEST_DOCK, and Widget_t::widget.
{
     XEvent event;
     Atom selection_atom = XInternAtom (w->app->dpy,"_NET_SYSTEM_TRAY_S0",False);
     Window tray = XGetSelectionOwner (w->app->dpy,selection_atom);
     Atom visualatom = XInternAtom(w->app->dpy, "_NET_SYSTEM_TRAY_VISUAL", False);
     VisualID value = XVisualIDFromVisual(DefaultVisual(w->app->dpy, DefaultScreen(w->app->dpy)));
     XChangeProperty(w->app->dpy, w->widget, visualatom, XA_VISUALID, 32,
             PropModeReplace, (unsigned char*)&value, 1);
     if ( tray != None)
         XSelectInput (w->app->dpy,tray,StructureNotifyMask);
     memset(&event, 0, sizeof(event));
     event.xclient.type = ClientMessage;
     event.xclient.window = tray;
     event.xclient.message_type = XInternAtom (w->app->dpy, "_NET_SYSTEM_TRAY_OPCODE", False );
     event.xclient.format = 32;
     event.xclient.data.l[0] = CurrentTime;
     event.xclient.data.l[1] = SYSTEM_TRAY_REQUEST_DOCK;
     event.xclient.data.l[2] = w->widget;
     event.xclient.data.l[3] = 0;
     event.xclient.data.l[4] = 0;
     XSendEvent(w->app->dpy, tray, False, NoEventMask, &event);
 }
show_tooltip()
void show_tooltip (Widget_t * wid)
show_tooltip - check if a Widget_t have a tooltip, and show it, if a tooltip is available.
Parameters
*wid - pointer to the Widget_t receiving the event
Returns
void
Definition at line 453 of file xwidget.c.
References Widget_t::app, Widget_t::childlist, Childlist_t::childs, Xputty::dpy, Childlist_t::elem, Widget_t::flags, IS_TOOLTIP, Widget_t::widget, and widget_show().
{
     int i = 0;
     for(;i<wid->childlist->elem;i++) {
         Widget_t *w = wid->childlist->childs[i];
         if (w->flags & IS_TOOLTIP) {
             unsigned int mask;
             int x, y, rx, ry;
             Window child, root;
             XQueryPointer(wid->app->dpy, wid->widget, &root, &child, &rx, &ry, &x, &y, &mask);
             int x1, y1;
             XTranslateCoordinates( wid->app->dpy, wid->widget, DefaultRootWindow(wid->app->dpy),
                                                                        x, y, &x1, &y1, &child );
             XMoveWindow(w->app->dpy,w->widget,x1+10, y1-10);
             widget_show(w);
             break;
         }
     }
 }
signal_connect_func()
void signal_connect_func (Widget_t * w, EventType type, void(*)() handler)
signal_connect_func - connect a event with a handler by EventType identifier, without type check
You must ensure that the handler coresponde to the event type
check EventType for more information
Parameters
*w - the Widget_t sending the event
type - the event type to connect
*handler - the handler to handle the event
Returns
void
Definition at line 359 of file xwidget.c.
References Func_t::adj_callback, ADJ_INTERN, BUTTON_PRESS, Func_t::button_press_callback, BUTTON_RELEASE, Func_t::button_release_callback, CONFIGURE, Func_t::configure_callback, CONFIGURE_NOTIFY, Func_t::configure_notify_callback, Func_t::dialog_callback, DIALOG_RESPONSE, ENTER, Func_t::enter_callback, EXPOSE, Func_t::expose_callback, Widget_t::func, KEY_PRESS, Func_t::key_press_callback, KEY_RELEASE, Func_t::key_release_callback, LEAVE, Func_t::leave_callback, MAP_NOTIFY, Func_t::map_notify_callback, MEM_FREE, Func_t::mem_free_callback, Func_t::motion_callback, POINTER_MOTION, USER, Func_t::user_callback, VALUE_CHANGED, and Func_t::value_changed_callback.
{
     switch(type) {
         case(EXPOSE):
             w->func.expose_callback = handler;
         break;
         case(CONFIGURE):
             w->func.configure_callback = handler;
         break;
         case(ENTER):
             w->func.enter_callback = handler;
         break;
         case(LEAVE):
             w->func.leave_callback = handler;
         break;
         case(ADJ_INTERN):
             w->func.adj_callback = handler;
         break;
         case(VALUE_CHANGED):
             w->func.value_changed_callback = handler;
         break;
         case(USER):
             w->func.user_callback = handler;
         break;
         case(MEM_FREE):
             w->func.mem_free_callback = handler;
         break;
         case(CONFIGURE_NOTIFY):
             w->func.configure_notify_callback = handler;
         break;
         case(MAP_NOTIFY):
             w->func.map_notify_callback = handler;
         break;
         case(DIALOG_RESPONSE):
             w->func.dialog_callback = handler;
         break;
         case(BUTTON_PRESS):
             w->func.button_press_callback = handler;
         break;
         case(BUTTON_RELEASE):
             w->func.button_release_callback = handler;
         break;
         case(POINTER_MOTION):
             w->func.motion_callback = handler;
         break;
         case( KEY_PRESS):
             w->func.key_press_callback = handler;
         break;
         case( KEY_RELEASE):
             w->func.key_release_callback = handler;
         break;
         default:
         break;
     }
 }
transparent_draw()
void transparent_draw (void * wid, void * user_data)
transparent_draw - copy parent surface to child surface
you usaualy didn't need to call this, it's used automaticaly when a Widget_t have set the flag USE_TRANSPARENCY
this is the default setting for Widget_t
Parameters
*wid - pointer to the Widget_t receiving the event
*user_data - void pointer to attached user_data
Returns
void
Definition at line 495 of file xwidget.c.
References _propagate_child_expose(), Widget_t::app, Widget_t::buffer, Widget_t::cr, Widget_t::crb, debug_print, Xputty::dpy, Func_t::expose_callback, Widget_t::flags, Widget_t::func, Widget_t::parent, USE_TRANSPARENCY, and Widget_t::widget.
{
     Widget_t *wid = (Widget_t*)w_;
     cairo_push_group (wid->cr);
     if (wid->flags & USE_TRANSPARENCY) {
         Widget_t *parent = (Widget_t*)wid->parent;
         XWindowAttributes attrs;
         XGetWindowAttributes(wid->app->dpy, wid->widget, &attrs);
         debug_print("Widget_t _transparency \n");
         cairo_set_source_surface (wid->crb, parent->buffer, -attrs.x, -attrs.y);
         cairo_paint (wid->crb);
     }
     cairo_push_group (wid->crb);
     wid->func.expose_callback(wid, user_data);
     cairo_pop_group_to_source (wid->crb);
     cairo_paint (wid->crb);
     cairo_set_source_surface (wid->cr, wid->buffer,0,0);
     cairo_paint (wid->cr);
     cairo_pop_group_to_source (wid->cr);
     cairo_paint (wid->cr);
     _propagate_child_expose(wid);
 }
widget_event_loop()
void widget_event_loop (void * w_, void * event, Xputty * main, void * user_data)
widget_event_loop - the internal widget event loop
Parameters
*w - void pointer to the Widget_t receiving the event
*event - void pointer to the XEvent
*main - void pointer to the Xputty *main struct running the event loop
*user_data - void pointer to attached user_data
Returns
void
Definition at line 523 of file xwidget.c.
References _button_press(), _check_enum(), _check_grab(), _check_keymap(), _has_pointer(), _hide_all_tooltips(), adj_set_motion_state(), Widget_t::app, Func_t::button_release_callback, Widget_t::childlist, childlist_has_child(), Childlist_t::childs, Func_t::configure_callback, debug_print, destroy_widget(), Xputty::dpy, Func_t::enter_callback, Widget_t::flags, Widget_t::func, HAS_FOCUS, HAS_POINTER, HAS_TOOLTIP, hide_tooltip(), Func_t::key_press_callback, Func_t::key_release_callback, Func_t::leave_callback, Func_t::motion_callback, NO_AUTOREPEAT, quit_widget(), show_tooltip(), Widget_t::state, transparent_draw(), Widget_t::widget, and Widget_t::x.
{
     Widget_t *wid = (Widget_t*)w_;
     XEvent *xev = (XEvent*)event;
     if (XFilterEvent(xev, wid->widget))
         return;
     switch(xev->type) {
         case ConfigureNotify:
             wid->func.configure_callback(w_, user_data);
             //transparent_draw(w_, user_data);
             debug_print("Widget_t ConfigureNotify \n");
         break;
         case Expose:
             if (xev->xexpose.count == 0) {
                 transparent_draw(w_, user_data);
                 debug_print("Widget_t Expose \n");
             }
         break;
         case ButtonPress:
             if (wid->flags & HAS_TOOLTIP) hide_tooltip(wid);
             _button_press(wid, &xev->xbutton, user_data);
             debug_print("Widget_t  ButtonPress %i\n", xev->xbutton.button);
         break;
         case ButtonRelease:
             _check_grab(wid, &xev->xbutton, main);
             _has_pointer(wid, &xev->xbutton);
             if(wid->flags & HAS_POINTER) wid->state = 1;
             else wid->state = 0;
             _check_enum(wid, &xev->xbutton);
             wid->func.button_release_callback(w_, &xev->xbutton, user_data);
             debug_print("Widget_t  ButtonRelease %i\n", xev->xbutton.button);
         break;
         case KeyPress:
             _check_keymap(wid, xev->xkey);
             wid->func.key_press_callback(w_, &xev->xkey, user_data);
             debug_print("Widget_t KeyPress %u\n", xev->xkey.keycode);
         break;
         case KeyRelease: {
             unsigned short is_retriggered = 0;
             if(wid->flags & NO_AUTOREPEAT) {
                 if (XEventsQueued(main->dpy, QueuedAlready)) {
                     XEvent nev;
                     XPeekEvent(main->dpy, &nev);
                     if (nev.type == KeyPress && nev.xkey.time == xev->xkey.time &&
                         nev.xkey.keycode == xev->xkey.keycode &&
                         (nev.xkey.keycode > 119 || nev.xkey.keycode < 110)) {
                         XNextEvent (main->dpy, xev);
                         is_retriggered = 1;
                     }
                 }
             }
             if (!is_retriggered) {
                 wid->func.key_release_callback(w_, &xev->xkey, user_data);
                 debug_print("Widget_t KeyRelease %u\n", xev->xkey.keycode);
             }
         }
         break;
         case LeaveNotify:
             wid->flags &= ~HAS_FOCUS;
             if(!(xev->xcrossing.state & Button1Mask)) {
                 wid->state = 0;
                 wid->func.leave_callback(w_, user_data);
             }
             if (wid->flags & HAS_TOOLTIP) hide_tooltip(wid);
             debug_print("Widget_t LeaveNotify \n");
         break;
         case EnterNotify:
             wid->flags |= HAS_FOCUS;
             if(!(xev->xcrossing.state & Button1Mask)) {
                 wid->state = 1;
                 wid->func.enter_callback(w_, user_data);
                 if (wid->flags & HAS_TOOLTIP) show_tooltip(wid);
                 else _hide_all_tooltips(wid);
             }
             debug_print("Widget_t EnterNotify \n");
         break;
         case MotionNotify:
             adj_set_motion_state(wid, xev->xmotion.x, xev->xmotion.y);
             wid->func.motion_callback(w_,&xev->xmotion, user_data);
             debug_print("Widget_t MotionNotify x = %i Y = %i \n",xev->xmotion.x,xev->xmotion.y );
         break;
         case ClientMessage:
             if (xev->xclient.message_type == XInternAtom(wid->app->dpy, "WIDGET_DESTROY", 1)) {
                 int ch = childlist_has_child(wid->childlist);
                 if (ch) {
                     int i = ch;
                     for(;i>0;i--) {
                         quit_widget(wid->childlist->childs[i-1]);
                     }
                     quit_widget(wid);
                 } else {
                     destroy_widget(wid,main);
                 }
             }
         default:
         break;
     }
 }
widget_hide()
void widget_hide (Widget_t * w)
widget_hide - unmap/hide a Widget_t
Parameters
*w - pointer to the Widget_t to unmap
Returns
void
Definition at line 423 of file xwidget.c.
References Widget_t::app, Widget_t::childlist, Childlist_t::childs, Xputty::dpy, Childlist_t::elem, and Widget_t::widget.
{
     int i=0;
     for(;i<w->childlist->elem;i++) {
         widget_hide(w->childlist->childs[i]);
     }
     XUnmapWindow(w->app->dpy, w->widget);
 }
widget_reset_scale()
void widget_reset_scale (Widget_t * w)
widget_reset_scale - used to reset scaling mode after a image surface is drawn to the Widget_t surface with widget_set_scale()
Parameters
*w - pointer to the Widget_t sending the request
Returns
void
Definition at line 133 of file xwidget.c.
References Widget_t::crb, Resize_t::cscale_x, Resize_t::cscale_y, and Widget_t::scale.
{
     cairo_scale(w->crb, w->scale.cscale_x,w->scale.cscale_y);
 }
widget_set_scale()
void widget_set_scale (Widget_t * w)
widget_set_scale - set scaling mode to scale a image surface to the size of the Widget_t surface
Parameters
*w - pointer to the Widget_t sending the request
Returns
void
Definition at line 137 of file xwidget.c.
References Widget_t::crb, Resize_t::rcscale_x, Resize_t::rcscale_y, and Widget_t::scale.
{
     cairo_scale(w->crb, w->scale.rcscale_x,w->scale.rcscale_y);
 }
widget_set_title()
void widget_set_title (Widget_t * w, const char * title)
widget_set_title - set window title for a Widget_t
Parameters
*w - pointer to the Widget_t to set the title
*title - the title to store
Returns
void
Definition at line 414 of file xwidget.c.
References Widget_t::app, Xputty::dpy, and Widget_t::widget.
{
     XStoreName(w->app->dpy, w->widget, title);
 }
widget_show()
void widget_show (Widget_t * w)
widget_show - map/show widget
Parameters
*w - pointer to the Widget_t to map
Returns
void
Definition at line 418 of file xwidget.c.
References Widget_t::app, Xputty::dpy, Widget_t::func, Func_t::map_notify_callback, and Widget_t::widget.
{
     w->func.map_notify_callback(w, NULL);
     XMapWindow(w->app->dpy, w->widget);
 }
widget_show_all()
void widget_show_all (Widget_t * w)
widget_show_all - map/show Widget_t with all childs
Parameters
*w - pointer to the Widget_t to map
Returns
void
Definition at line 431 of file xwidget.c.
References Widget_t::app, Widget_t::childlist, Childlist_t::childs, Xputty::dpy, Childlist_t::elem, Widget_t::flags, Widget_t::func, IS_POPUP, IS_TOOLTIP, Func_t::map_notify_callback, and Widget_t::widget.
{
     if (w->flags & IS_POPUP || w->flags & IS_TOOLTIP) {
         return;
     } else {
         w->func.map_notify_callback(w, NULL);
         XMapWindow(w->app->dpy, w->widget);
         int i=0;
         for(;i<w->childlist->elem;i++) {
             widget_show_all(w->childlist->childs[i]);
         }
     }
 }